### ISSUE TITLE
[Feature] prevent user from saving configuration if name has spaces

### ISSUE THREAD

**Issue by Heus-Sueh** [vikdevelop/SaveDesktop#10]
I almost opened an issue thinking it was a bug, because the program shows the message that the configuration was saved but it doesn't appear in the folder

**Comment by vikdevelop** [comment]
This is an interesting tip. I will add it to the next release.

**Comment by vikdevelop** [comment]
I published a new version with message about using spaces in the file name on Flathub. It availables to download in a few hours.
