### ISSUE TITLE
Add ability to select items to import/export

### ISSUE THREAD

**Issue by marcinjahn** [vikdevelop/SaveDesktop#106]
Currently, only Flatpak apps is an optional item. I think it'd make sense to allow users to choose what they want to export/import. Desktop Icons? Themes? Flatpak apps? etc.

**Comment by vikdevelop** [comment]
Hello,
I don't understand, why users would select the items for saving configuration. The user awaits, all items of desktop configuration will be saved. I want it to be a simple application. Just the user clicks on the "Save" button and configuration will be saved. If he wants to also save Flatpak applications, click on the switch.

**Comment by marcinjahn** [comment]
It’s just a suggestion :)
I think this app could be useful when you’re formatting your PC. When you format, you usually do that because there’s too much shit on your current setup and you want to get rid of it. For example, you might have installed lots of custom icon packs, and you don’t really want to carry them over to the new installation. It would be useful to disable icons export in such a case.

**Comment by vikdevelop** [comment]
I may implement this in a future version.
