### ISSUE TITLE
Sync: Connect with other computer dialog to close by cancel twice

### ISSUE THREAD

**Issue by danieluhrinyi** [vikdevelop/SaveDesktop#126]
On the Sync tab of the application, when I want to close the dialog window of "Connect with other computer", the Cancel button has to be hit twice.

[sync_cancel_connectwithothercomputer.webm](https://github.com/vikdevelop/SaveDesktop/assets/12256895/707b12b1-c116-4731-a377-56c5e8b418b7)

**Comment by vikdevelop** [comment]
Hello,
it is strange because on my system, it works without the problems described in this issue. Just one click on the "cancel" button, and the dialog will close.
[cancel_button.webm](https://github.com/vikdevelop/SaveDesktop/assets/83600218/7acb5ece-737a-4ab8-87c1-ee70dbfcf964)

**Comment by danieluhrinyi** [comment]
I am on Debian 12 with GNOME 43.6.

**Comment by vikdevelop** [comment]
Does the same thing happen to you in the additional settings dialog for periodic saving?

**Comment by danieluhrinyi** [comment]
> Does the same thing happen to you in the additional settings dialog for periodic saving?

Yes, same thing. (Sorry for the late response.)

**Comment by vikdevelop** [comment]
You may need to close dialogues using the EsC key.
