### ISSUE TITLE
Sync app settings

### ISSUE THREAD

**Issue by frandavid100** [vikdevelop/SaveDesktop#147]
### The current problem or need

Besides syncing a list of installed flatpak apps, I would like to be able to install their settings and contents (e.g. notes in note taking apps). Would that be possible?

### Describe the solution you'd like

A new item is added to the "synced items" menu.

**Comment by vikdevelop** [comment]
Hello,
I've tried it before, without success. In most cases, only the SaveDesktop settings were saved, even if I allowed access to the `~/.var/app` folder.
So for now I won't add it unfortunately, maybe sometime in the future.
