### ISSUE TITLE
The application does not start after an update

### ISSUE THREAD

**Issue by vorons** [vikdevelop/SaveDesktop#15]
Hi!
After updating, the application does not start. When click on the application icon, nothing happens. When launching from the terminal, an error:
```
$ flatpak run io.github.vikdevelop.SaveDesktop

Traceback (most recent call last):
  File "/app/main_window.py", line 34, in <module>
    lang == 'ru.json'
NameError: name 'lang' is not defined. Did you mean: 'range'?
```

Version: 1.3

**Comment by vikdevelop** [comment]
Thanks for the heads-up. I have already corrected the error. I will release a corrected version on Flathub.

**Comment by vikdevelop** [comment]
New version with fixed this bug has been published on Flathub. It availables to download in a few hours.
