### ISSUE TITLE
bug:No backup created

### ISSUE THREAD

**Issue by j75** [vikdevelop/SaveDesktop#170]
### Linux distribution

Ubuntu 22.04

### Desktop Environment

Cinnamon

### Package type

Flatpak from Flathub

### Bug description

I selected a local folder to save the backup in - nothing is created.

However, I noticed the following messages on my console:
```
cp: cannot stat '/home/user/.local/share/backgrounds': No such file or directory
tar: ./cinnamon/applets: file changed as we read it
tar: ./cinnamon: file changed as we read it
tar: ./Cinnamon-pamela.sd.tar.gz: file changed as we read it
tar: .: file changed as we read it
mv: cannot create regular file '/run/user/<myid>/doc/e207c239/Cinnamon/Cinnamon-pamela.sd.tar.gz': Permission denied
```

**Comment by vikdevelop** [comment]
Hello, try to allow permission for your periodic saving folder in the Flatseal app, then open the SaveDesktop app and select the same folder for periodic saving again.

**Comment by vikdevelop** [comment]
Hello, try to allow permission for your folder in the Flatseal app, then open the SaveDesktop app and save configuration again.

**Comment by j75** [comment]
Yes, that was the problem!
Maybe you should add some lines in the README about that, and the link to the Flatseal app.
