### ISSUE TITLE
Save Nautilus scripts

### ISSUE THREAD

**Issue by iamgitcat** [vikdevelop/SaveDesktop#175]
### The current problem or need

As the app saves Nautilus extensions folder, it is strange that it ignores Nautilus scripts folder, both are maintained similar way to extend file manager functionality and you would like both to be restored/backuped.

### Describe the solution you'd like

Consider including scripts to backups too, they are valuable settings.

**Comment by vikdevelop** [comment]
Hello,
thank you for your feature request.
I will implement this feature in the future version of the SaveDesktop app.
