### ISSUE TITLE
Snap package creation and development thread

### ISSUE THREAD

**Issue by soumyaDghosh** [vikdevelop/SaveDesktop#176]
Creating this issue to discuss on the snap package. There needs some changes with complying the snap confinement. I will try to create PRs if possible. But, one thing that needs to be changed is the `home`. In snaps, `home` isn't directly assigned to `$HOME`, rather use, `$SNAP_REAL_HOME`. Most of the problems will be fixed there. And disable the flatpak apps thing in snap package, please.

**Comment by vikdevelop** [comment]
Hello, I disabled saving Flatpak apps in the Snap version and setted up the $SNAP_REAL_HOME in the `snapcraft.yaml`.

**Comment by soumyaDghosh** [comment]
Hey, thanks but as my PR has been merged, it's not needed anymore. And some changes are needed in the `snapcraft.yaml` itself. I'll try to fix them.

**Comment by vikdevelop** [comment]
I tried SaveDesktop in the snap version (from building snapcraft.yaml file), and the app works excelently. It works sync, periodic saving, manual import and saving. How does it look with the `savedesktop` application name assignment? My email that is linked to my Snapstore account is: super-vik1@protonmail.com.

**Comment by soumyaDghosh** [comment]
> My email that is linked to my Snapstore account is: [super-vik1@protonmail.com](mailto:super-vik1@protonmail.com).

Sent you the collaboration request.

> I tried SaveDesktop in the snap version (from building snapcraft.yaml file), and the app works excelently. It works sync, periodic saving, manual import and saving.

Are you testing on Fedora based distro? Because snap confinement often doesn't work in Fedora due to their regression to use SeLinux.

**Comment by vikdevelop** [comment]
> Are you testing on Fedora based distro? Because snap confinement often doesn't work in Fedora due to their regression to use SeLinux.
I can not release the successful build, because it requires the manual review. Why it happen?

**Comment by soumyaDghosh** [comment]
It's because of the dbus declarations. Kindly wait. I am working on that completely from scratch. Those declarations will not be necessary at all. Kindly wait a day or two.

**Comment by vikdevelop** [comment]
Once again, I was denied a build:
> Rejected by Alex Murray. “The personal-files interface is a super-privileged interface (https://snapcraft.io/docs/super-privileged-interfaces). If your snap legitimately requires this access, please follow the process for aliases, auto-connections and tracks (https://snapcraft.io/docs/process-for-aliases-auto-connections-and-tracks) and create a post in the 'store-requests' category requesting its use.” — Alex Murray

**Comment by soumyaDghosh** [comment]
Yup.. just as said there, personal files, `login-session-control` all these are super privileged and sensitive plugs. So, needs to make an auto connect in the forum. That's it.

**Comment by soumyaDghosh** [comment]
https://forum.snapcraft.io/t/autoconnect-request-for-snap-savedesktop/37592/2

Keep an eye on this. You might be called here for vetting.

**Comment by vikdevelop** [comment]
It looks like the reviewers don't care about the auto-connection requirement. Is it possible to use something else that would not require an auto-connect requirement, e.g. renaming the interface for personal files?

**Comment by soumyaDghosh** [comment]
Actually it's sprints going on. So, most of the reviewers are out in Riga. But until then as the name says, users can manually connect to the plug with a command or from the settings app in Ubuntu. But still we'll need to have the option to upload it. Kindly wait and have patience. A lot of snaps are in the queue due to this summit and sprint. And don't worry, I'll handle the snap package.

**Comment by soumyaDghosh** [comment]
@vikdevelop Kindly look into the forum, they need you for publisher vetting
