### ISSUE TITLE
feature_request: Option to create online backups using GitHub / GitLab

### ISSUE THREAD

**Issue by onlyreportingissues** [vikdevelop/SaveDesktop#195]
### The current problem or need

Online backup solution.

### Describe the solution you'd like

Basically what this outdated GNOME extension does: https://github.com/oae/gnome-shell-extensions-sync

**Comment by vikdevelop** [comment]
Hello, 
thank you for your feature request.

The maximum size for the file in the repository itself is 25 MB and on the page with releases is 1 GB.

Also you need to login on GitHub via Git which is unavailable in Flatpak Sandbox environment, with your username and access token that is necessary often reactivate.

So far I will not implement it for the next release, maybe, sometimes in the future.
