### ISSUE TITLE
feature_request: Automatic cleanup for old saves

### ISSUE THREAD

**Issue by eriolloan** [vikdevelop/SaveDesktop#203]
### The current problem or need

I'm syncing daily saves to a paid nextcloud server and as the archived are around 60Mo I regularly delete them to preserve space.

In addition, I might be wrong but I'm not sure there's such a big use case where you need to restore a one-year old config.

### Describe the solution you'd like

It would be nice to have the option to limit the number of saves (or maybe combined size, which would more easily apply to all save frequencies), and have the oldest deleted when creating a new one. 

From a UX standpoint:

If indeed there is no widespread need for archiving all backups ever produced, I'd suggest to set it on by default (with sensible default quantity/weight value). 
In this scenario the application is ready to use out of the box, the user just change the frequency if needed, while users needing to store all their saves have just one more action to perform (tick the appropriate box).

Anyway your application is a lifesaver as is, so thank you !

**Comment by vikdevelop** [comment]
Hello, and thank you for your feature request. 
But I am afraid, I don't really understand your request. Do you save files manually or through periodic saving and transfer them to Nextcloud (SaveDesktop doesn't support transferring files to cloud services)? If you're saving files periodically with the periodic saving function, the original backup file is overwritten by the new file. If you save files manually and if you keep the same filename, the original file is also overwritten by the new file.

**Comment by eriolloan** [comment]
That sounds strange... I have the frequency set on daily and `confg_XXXX-XX-XX` archives are piling up in the target directory.

(nevermind the Nextcloud thing, the target directory is on-disk and simply synced)

I may be doing something wrong then.

Le 17 janvier 2024 20:54:14 GMT+01:00, vikdevelop ***@***.***> a écrit :

**Comment by vikdevelop** [comment]
What version of SaveDesktop do you have? Are you using the Flatpak version or the native version?

**Comment by eriolloan** [comment]
Using the flatpak version 2.9.2

Le 17 janvier 2024 23:46:17 GMT+01:00, vikdevelop ***@***.***> a écrit :

**Comment by vikdevelop** [comment]
In the version you mentioned, this feature was not yet available, as it is a very old version (~3 months), please update SaveDesktop to the latest version.

**Comment by eriolloan** [comment]
You're right, I was a few versions behind.

Updated to the latest Flatpak on flathub (3.0.0), thanks !
