### ISSUE TITLE
Settings are not save on Synology drive folder

### ISSUE THREAD

**Issue by stephan1827** [vikdevelop/SaveDesktop#220]
### Linux distribution

Zorin 17 Pro

### Desktop Environment

GNOME

### Version of the SaveDesktop app

3.1

### Package type

Flatpak from Flathub

### Bug description

Saving the desktop settings to the home folder works great. But trying to save it to a Synology drive folder does not. The app says it saved the settings successful but there is no file. Syncing through a file is the same problem. Permissions should be ok. Are there any logs I can check to trace the problem?

**Comment by vikdevelop** [comment]
Hello, please open the Terminal (Ctrl+Alt+T) and enter this command:
```
flatpak run io.github.vikdevelop.SaveDesktop
```
and then copy the output and paste it here.

**Comment by vikdevelop** [comment]
Any updates on this?
For getting output log it is not other option.

**Comment by vikdevelop** [comment]
Alternatively, you can use the native version of the SaveDesktop app and try so if saving to the Synology folder works. The instructions are [here](https://github.com/vikdevelop/SaveDesktop?tab=readme-ov-file#installation).

**Comment by vikdevelop** [comment]
Alternatively, you can try the native version of the SaveDesktop app and see if saving to the Synology folder works. The instructions are [here](https://github.com/vikdevelop/SaveDesktop?tab=readme-ov-file#installation).

**Comment by stephan1827** [comment]
Here is what I get...it seems that there is a permission issue but I can copy the files through Nautilus just fine.

```
flatpak run io.github.vikdevelop.SaveDesktop
/app/main_window.py:104: DeprecationWarning: Adw.ViewSwitcherTitle.set_stack is deprecated
  self.switcher_title.set_stack(self.stack)
/app/main_window.py:105: DeprecationWarning: Adw.ViewSwitcherTitle.set_title is deprecated
  self.switcher_title.set_title("")

(main_window.py:3): Adwaita-CRITICAL **: 16:53:48.532: adw_status_page_set_child: assertion 'gtk_widget_get_parent (child) == NULL' failed

(main_window.py:3): Adwaita-CRITICAL **: 16:53:48.532: adw_status_page_set_child: assertion 'gtk_widget_get_parent (child) == NULL' failed
ls: cannot access '/home/stephan/.local/share/flatpak/app': No such file or directory
cp: cannot stat '/home/stephan/.local/share/gnome-background-properties': No such file or directory
cp: cannot stat '/home/stephan/.local/share/nautilus-python': No such file or directory
cp: cannot stat '/home/stephan/.config/gnome-control-center': No such file or directory
tar: .: file changed as we read it
mv: replace '/run/user/1000/doc/a1a0b3db/SaveDesktop/BigMacZorin.sd.tar.gz', overriding mode 0444 (r--r--r--)? y
mv: inter-device move failed: './cfg.sd.tar.gz' to '/run/user/1000/doc/a1a0b3db/SaveDesktop/BigMacZorin.sd.tar.gz'; unable to remove target: Permission denied
```

**Comment by vikdevelop** [comment]
> Alternatively, you can try the native version of the SaveDesktop app and see if saving to the Synology folder works. The instructions are [here](https://github.com/vikdevelop/SaveDesktop?tab=readme-ov-file#installation).

As I mentioned above, you can try to use the native version. It should be work with your Linux distribution.

**Comment by stephan1827** [comment]
Thx for the quick response, when I try to install native I get the following error messages

`sudo python3 /tmp/savedesktop-tmp/native/native_installer.py --install
--2024-02-07 07:57:17--  https://github.com/vikdevelop/SaveDesktop/archive/refs/tags/3.1n.tar.gz
Resolving github.com (github.com)... 140.82.121.3
Connecting to github.com (github.com)|140.82.121.3|:443... connected.
HTTP request sent, awaiting response... 302 Found
Location: https://codeload.github.com/vikdevelop/SaveDesktop/tar.gz/refs/tags/3.1n [following]
--2024-02-07 07:57:18--  https://codeload.github.com/vikdevelop/SaveDesktop/tar.gz/refs/tags/3.1n
Resolving codeload.github.com (codeload.github.com)... 140.82.121.9
Connecting to codeload.github.com (codeload.github.com)|140.82.121.9|:443... connected.
HTTP request sent, awaiting response... 200 OK
Length: 287181 (280K) [application/x-gzip]
Saving to: ‘3.1n.tar.gz’

3.1n.tar.gz                                     100%[====================================================================================================>] 280,45K  --.-KB/s    in 0,06s   

2024-02-07 07:57:18 (4,56 MB/s) - ‘3.1n.tar.gz’ saved [287181/287181]

native/install_native.sh: 14: cannot create /root/.config/autostart/io.github.vikdevelop.SaveDesktop.Updater.desktop: Directory nonexistent
install: cannot stat 'flatpak/symbolic-icons/edit-symbolic.svg': No such file or directory
mkdir: cannot create directory ‘/root/.cache/io.github.vikdevelop.SaveDesktop’: File exists
mkdir: cannot create directory ‘/root/.local/share/io.github.vikdevelop.SaveDesktop’: File exists
SaveDesktop has been installed! You can run it with this command: "savedesktop" or "~/.local/bin/savedesktop".
`

**Comment by stephan1827** [comment]
Thx, installing the native version seems to work

**Comment by vikdevelop** [comment]
So, does saving to the Synology folder works or not?

**Comment by stephan1827** [comment]
Yes, it does :-)

**Comment by vikdevelop** [comment]
So this is the problem with Flatpak permissions, I can't do anything about it, because permission for allowing access to Synology or similar cloud storage is not exist.
