### ISSUE TITLE
bug:  You have an unsupported environment installed.

### ISSUE THREAD

**Issue by richtrefz** [vikdevelop/SaveDesktop#222]
### Linux distribution

Fedora Linux 39

### Desktop Environment

KDE Plasma

### Version of the SaveDesktop app

3.1.1

### Package type

Flatpak from Flathub

### Bug description

You have an unsupported environment installed.
Please use one of these environments: GNOME, Xfce, Budgie, Cinnamon, COSMIC, Pantheon,
KDE Plasma, MATE.

KDE Plasma Version: 5.27.10
KDE Frameworks Version: 5.13.0
Qt Version: 5.15.12
Kernel Version: 6.7.4-200.fc39.x86_64 (64-bit)
Graphics Platform: X11

**Comment by vikdevelop** [comment]
Hello,
I tried to use the app in the Linux distribution that you mentioned, and the app works without any problems.
So it would be a good idea if you opened Terminal (Ctrl+Alt+T) and ran this command, from which you copied its output and pasted it here:
```
flatpak run io.github.vikdevelop.SaveDesktop
```

**Comment by vikdevelop** [comment]
Hello,
may you have other  'XDG_CURRENT_DESKTOP' variable? The correct variable should be 'KDE'. So try to open terminal and enter this command and their output, paste here:
```
echo $XDG_CURRENT_DESKTOP
```

**Comment by vikdevelop** [comment]
Hello,
maybe you have other output of '$XDG_CURRENT_DESKTOP' variable. The correct output of this variable in this case should be 'KDE'. So try to open a terminal (Ctrl+Alt+T) and enter this command, and paste their output here:
```
echo $XDG_CURRENT_DESKTOP
```

**Comment by richtrefz** [comment]
Sorry for my confusion.  XDG_CURRENT_DESKTOP was getting cleared before I ran SaveDesktop

**Comment by vikdevelop** [comment]
This is the problem. Because you have empty $XDG_CURRENT_DESKTOP value, SaveDesktop shows the error message. I don't quite know, why you have empty $XDG_CURRENT_DESKTOP, because value of the variable in the default installation in your distro is 'KDE'.

**Comment by richtrefz** [comment]
It's something I did and I resolved it.  Thank you for helping and sorry for the inconvenience.
