### ISSUE TITLE
bug: Not saving, or taking forever

### ISSUE THREAD

**Issue by BarbzYHOOL** [vikdevelop/SaveDesktop#224]
### Linux distribution

pop os 22.04

### Desktop Environment

GNOME

### Version of the SaveDesktop app

3.1.1

### Package type

Flatpak from Flathub

### Bug description

![image](https://github.com/vikdevelop/SaveDesktop/assets/29780637/ca86376a-20a9-4bf4-aaab-8fda971960d8)
```

(process:3): Gtk-WARNING **: 03:39:11.313: Locale not supported by C library.
	Using the fallback 'C' locale.

(process:75280): GLib-CRITICAL **: 03:39:11.539: Failed to set scheduler settings: Operation not permitted
/app/main_window.py:104: DeprecationWarning: Adw.ViewSwitcherTitle.set_stack is deprecated
  self.switcher_title.set_stack(self.stack)
/app/main_window.py:105: DeprecationWarning: Adw.ViewSwitcherTitle.set_title is deprecated
  self.switcher_title.set_title("")

(main_window.py:3): Adwaita-CRITICAL **: 03:39:11.781: adw_status_page_set_child: assertion 'gtk_widget_get_parent (child) == NULL' failed

(main_window.py:3): Adwaita-CRITICAL **: 03:39:11.783: adw_status_page_set_child: assertion 'gtk_widget_get_parent (child) == NULL' failed


```` nothing else in terminal

the file is not saved aftr 5 minutes

**Comment by vikdevelop** [comment]
Hello,
The time to save the configuration in this case depends on how big your `~/.var/app` folder (the folder for saving Flatpak application data) is, as well as other configuration folders, so it may take more than 5 minutes. When saving the configuration, you can look in the `~/.var/app/io.github.vikdevelop.SaveDesktop/cache/tmp/` directory, you will see the `save_config` folder there. If it disappears after a while, it means the configuration has been saved.

**Comment by BarbzYHOOL** [comment]
ok thank you, i just want to try it out so i disabled the saving of flatpak data

It worked fine however, as usual with flatpaks, saving to /tmp didn't work so i had to save to ~/Downloads -__-

Also the app doesn't tell you what it saves, which should be the case

**Comment by vikdevelop** [comment]
Saving to /tmp directory doesn't work, due to Flatpak permissions.

If you want to show, what directories will be saved, you can view it [here](https://github.com/vikdevelop/SaveDesktop?tab=readme-ov-file#savedesktop-can-save).
