### ISSUE TITLE
feature_request: save individual app data

### ISSUE THREAD

**Issue by back-lacking** [vikdevelop/SaveDesktop#230]
### The current problem or need

i would like save the user data of my flat paks but not all of them. i would like to exclude some flatpaks from the save in order to make my save smaller and to remove unneeded data. 

### Describe the solution you'd like

within the "user data of installed flatpak apps" toggle, include a scrollable list of apps and you can choose which flatpak you want to save the data of

**Comment by vikdevelop** [comment]
Hello, thank you for your feature request. I may add this feature to the future version.

**Comment by vikdevelop** [comment]
Hello, and thank you for your feature request. I agree that a user could have data from many apps, that he doesn't use, because he uninstalls them. I will try to implement this feature in the next version of the SaveDesktop app.
