### ISSUE TITLE
feature_request: Progress indicator/feedback

### ISSUE THREAD

**Issue by Vovkiv** [vikdevelop/SaveDesktop#232]
### The current problem or need

Currently, SaveDesktop has poor communication with user about state of saving/importing data, nor does have option to stop saving.
It can be made more user-friendly by adding better feedback to user (other then toast message that can be closed), what exactly happens and when it will be done.

### Describe the solution you'd like

Same can be done for importing as well, but here mockup for saving data:
![зображення](https://github.com/vikdevelop/SaveDesktop/assets/54743395/da3912b3-938e-4a5c-a24b-b2be593836f9)
* Here user can see that saving is in process and can't accidentally close this menu (unlike toast message).
* If possible, show how much time/percentage left until data will be save, otherwise show rotating spinner, as many software do in cases like this.
* There should be button to stop saving, in case if user wants to stop process, for example, they picked wrong directory to save data.
* Maybe there can be added more info about current operation, like what archive name will be and where it will be stored, but this is up to debate.
* Also, user shouldn't be able to start new save process until last one ends, because it doesn't make much sense and currently program doesn't communicate what will happen if user start new saving progress when last one not finished yet.

**Comment by vikdevelop** [comment]
Hello, thank your feature request.
You're right. The current solution is not ideal, so I will implement this feature in the future version of the SaveDesktop app. Because I don't understand, how to implement progress bar, I will use spinner.

**Comment by vikdevelop** [comment]
I added this feature to the rel3-2 branch, and it looks like this:
![Screenshot from 2024-03-13 21-24-58](https://github.com/vikdevelop/SaveDesktop/assets/83600218/08c7a87d-2209-4ad2-a6dc-99778996b80c)
![Screenshot from 2024-03-13 21-24-43](https://github.com/vikdevelop/SaveDesktop/assets/83600218/3c4ea36c-131e-494e-9caf-7d981b0b072f)
It looks the same (only with different texts) when importing the configuration.
Also, I added prints of the individual events (saving icons, themes, and backgrounds) during saving and importing configuration.
The release I planned release on March 24, 2024.
What do you think about it?

**Comment by Vovkiv** [comment]
Path should probably starts on newline to avoid this kinda awkward word wrapping.

And wording for where file is stored could be probably changed:
"Your Desktop Environment configuration will be saved here:
/path/to/file.gz"
"Directory" part is kinda redundant, since you specify full path, not just directory.

Other then that, I like it!
