### ISSUE TITLE
Is this supposed to also install extensions in gnome?

### ISSUE THREAD

**Issue by ldiane** [vikdevelop/SaveDesktop#24]
Hi,

First of all thank you for this fantastic app!

I have been doing a lot of tinkering lately and I think that after restoring a previous configuration the app installed my extensions as well as restoring their config files on gnome (this happened only once so I am not sure if it really does so, I could be trippin)

Does the app do it?
I am asking because I haven't been able to redo it ever since. After that first time the app only restores extension configuration without installing extensions. If I install my extensions manually the configuration is still there.

Thank you

Edit: also is there a command that I can use to launch a restore of a previously saved desktop?

**Comment by vikdevelop** [comment]
Hello, SaveDesktop can save GNOME Shell extensions that are installed in the` ~/.local/share/gnome-shell/extensions` directory. After importing the configuration and logging out of the system and logging back in, the extensions should be activated. So it worked for me without any problems.

**Comment by ldiane** [comment]
Ok I confirm my extensions are installed in that directory. I just tried restoring my backup file to a brand new arch vm with gnome but it doesn't install the extensions, it just puts in place configuration files.
However if I install the extensions manually the configuration files are applied. I can provide further info if needed

**Comment by ldiane** [comment]
They don't appear in extension manager at all. Also I just checked the `~/.local/share/gnome-shell/extensions` directory after restoring the tar file and only 1 of the 4 extensions i had previously backed up was there

**Comment by ldiane** [comment]
I solved the issue, will post relevant info soon

**Comment by ldiane** [comment]
So this is what is happening:
In the `sd.tar.gz` file in the path `/./gnome-shell/extensions/` there is only 1 extension saved despite me backing up 4 of them.
In the `/home/user/Downloads/SaveDesktop/.2023-03-16/gnome-shell/extensions` path there are all my extensions saved.

I can restore them manually in the new VM to `~/.local/share/gnome-shell/extensions`. After a logout my extensions are correctly installed and configured. I am not entirely sure why they are not in the tar file

**Comment by vikdevelop** [comment]
There's probably a problem with Flatpak permissions. Try enabling access to the entire home directory in Flatseal or run the following command in the terminal: `flatpak run --filesystem=home io.github.vikdevelop.SaveDesktop`
Let me know, if it works or not.

**Comment by ldiane** [comment]
Yes now it works properly!
Thank you very much for the support
