### ISSUE TITLE
feature_request: use AdwToolbarView

### ISSUE THREAD

**Issue by bragefuglseth** [vikdevelop/SaveDesktop#246]
### The current problem or need

SaveDesktop currently uses GTK’s built-in title bar functionality, which separates the title bar from the window and makes it look out of place among other GNOME apps

### Describe the solution you'd like

Switch to using an [Adw.ToolbarView](https://gnome.pages.gitlab.gnome.org/libadwaita/doc/main/class.ToolbarView.html) with the header bar as a top child, to make it blend in with the window itself.

**Comment by vikdevelop** [comment]
Hello, 
thank you for your feature request. 
I will try to implement this in the next version of the app.

**Comment by vikdevelop** [comment]
I released a new version that uses Adw.ToolbarView. It is available to download in a few hours.
