### ISSUE TITLE
bug: Unable to save any backup

### ISSUE THREAD

**Issue by SoulRaven** [vikdevelop/SaveDesktop#251]
### Linux distribution

Pop!_OS 22.04 LTS

### Desktop Environment

COSMIC (Pop!_OS)

### Version of the SaveDesktop app

3.2.1

### Package type

Flatpak from Flathub

### Bug description

i have try many times to save any backup, but is not working.
i get this message, even if the location has 1TB of space.
The location for saving is a mount drive with user permissions.

> Error copying directory /home/soulraven/.var/app/net.displaycal.DisplayCAL: [Errno 28] No space left on device: '/home/soulraven/.var/app/io.github.vikdevelop.SaveDesktop/cache/tmp/save_config/app/net.displaycal.DisplayCAL'
> Error copying directory /home/soulraven/.var/app/net.codeindustry.MasterPDFEditor: [Errno 28] No space left on device: '/home/soulraven/.var/app/io.github.vikdevelop.SaveDesktop/cache/tmp/save_config/app/net.codeindustry.MasterPDFEditor'
> Error copying directory /home/soulraven/.var/app/org.inkscape.Inkscape: [Errno 28] No space left on device: '/home/soulraven/.var/app/io.github.vikdevelop.SaveDesktop/cache/tmp/save_config/app/org.inkscape.Inkscape'
> Error copying directory /home/soulraven/.var/app/com.brave.Browser: [Errno 28] No space left on device: '/home/soulraven/.var/app/io.github.vikdevelop.SaveDesktop/cache/tmp/save_config/app/com.brave.Browser'
> Error copying directory /home/soulraven/.var/app/io.gitlab.adhami3310.Converter: [Errno 28] No space left on device: '/home/soulraven/.var/app/io.github.vikdevelop.SaveDesktop/cache/tmp/save_config/app/io.gitlab.adhami3310.Converter'
> Error copying directory /home/soulraven/.var/app/org.kde.dolphin: [Errno 28] No space left on device: '/home/soulraven/.var/app/io.github.vikdevelop.SaveDesktop/cache/tmp/save_config/app/org.kde.dolphin'
> Error copying directory /home/soulraven/.var/app/com.github.wwmm.easyeffects: [Errno 28] No space left on device: '/home/soulraven/.var/app/io.github.vikdevelop.SaveDesktop/cache/tmp/save_config/app/com.github.wwmm.easyeffects'
> Traceback (most recent call last):
>   File "/app/config.py", line 279, in <module>
>     Save()
>   File "/app/config.py", line 108, in __init__
>     os.makedirs(f"{destdir}/io.github.vikdevelop.SaveDesktop", exist_ok=True)
>   File "<frozen os>", line 225, in makedirs
> OSError: [Errno 28] No space left on device: '/home/soulraven/.var/app/io.github.vikdevelop.SaveDesktop/cache/tmp/save_config/app/io.github.vikdevelop.SaveDesktop'

**Comment by vikdevelop** [comment]
Hello,
you can try these commands for showing free disk space: (it is possible that the /home partition is full, if you have it separated from the root directory)
`df -h` - This command displays disk usage and free space information for all attached partitions.
`lsblk` - This command displays information about the disk and partitions, including size and usage.

**Comment by SoulRaven** [comment]
> Filesystem               Size  Used Avail Use% Mounted on
> tmpfs                    3.2G  3.6M  3.2G   1% /run
> efivarfs                 128K  108K   16K  88% /sys/firmware/efi/efivars
> /dev/nvme0n1p3           220G   98G  111G  47% /
> tmpfs                     16G     0   16G   0% /dev/shm
> tmpfs                    5.0M     0  5.0M   0% /run/lock
> /dev/nvme0n1p1          1020M  275M  746M  27% /boot/efi
> /dev/nvme0n1p2           4.0G  2.9G  1.2G  71% /recovery
> /dev/sda1                916G  9.9G  860G   2% /mnt/DEV
> /dev/sdc1                916G   63G  807G   8% /mnt/WORK
> /dev/sdb1                916G  3.1G  867G   1% /mnt/MEDIA
> /dev/sdd1                586G   97G  460G  18% /mnt/640GB
> /dev/sde1                458G   30G  405G   7% /mnt/500GB
> tmpfs                    3.2G   97M  3.1G   3% /run/user/1000
> //192.168.2.20/Business  9.1T  2.2T  6.9T  25% /mnt/NAS2D8D20/Business
> //192.168.2.20/Media     9.1T  2.2T  6.9T  25% /mnt/NAS2D8D20/Media

> NAME          MAJ:MIN RM   SIZE RO TYPE  MOUNTPOINTS
> loop0           7:0    0     4K  1 loop  /snap/bare/5
> loop1           7:1    0  55.7M  1 loop  /snap/core18/2812
> loop2           7:2    0  74.1M  1 loop  /snap/core22/1033
> loop3           7:3    0  74.2M  1 loop  /snap/core22/1122
> loop4           7:4    0 164.8M  1 loop  /snap/gnome-3-28-1804/198
> loop5           7:5    0   497M  1 loop  /snap/gnome-42-2204/141
> loop6           7:6    0 504.2M  1 loop  /snap/gnome-42-2204/172
> loop7           7:7    0   8.8M  1 loop  /snap/grammarcheck/1
> loop8           7:8    0  91.7M  1 loop  /snap/gtk-common-themes/1535
> loop9           7:9    0  12.9M  1 loop  /snap/snap-store/1113
> loop10          7:10   0  12.3M  1 loop  /snap/snap-store/959
> loop11          7:11   0  40.4M  1 loop  /snap/snapd/20671
> loop12          7:12   0  39.1M  1 loop  /snap/snapd/21184
> sda             8:0    0 931.5G  0 disk  
> └─sda1          8:1    0 931.5G  0 part  /mnt/DEV
> sdb             8:16   0 931.5G  0 disk  
> └─sdb1          8:17   0 931.5G  0 part  /mnt/MEDIA
> sdc             8:32   0 931.5G  0 disk  
> └─sdc1          8:33   0 931.5G  0 part  /mnt/WORK
> sdd             8:48   0 596.2G  0 disk  
> └─sdd1          8:49   0 596.2G  0 part  /mnt/640GB
> sde             8:64   0 465.8G  0 disk  
> └─sde1          8:65   0 465.8G  0 part  /mnt/500GB
> zram0         251:0    0    16G  0 disk  [SWAP]
> nvme0n1       259:0    0 232.9G  0 disk  
> ├─nvme0n1p1   259:1    0  1022M  0 part  /boot/efi
> ├─nvme0n1p2   259:2    0     4G  0 part  /recovery
> ├─nvme0n1p3   259:3    0 223.9G  0 part  /
> └─nvme0n1p4   259:4    0     4G  0 part  
>   └─cryptswap 252:0    0     4G  0 crypt [SWAP]

**Comment by vikdevelop** [comment]
Have you a partitioned /home or part of the root directory?
As I wrote, you can try clearing the cache by deleting the folder mentioned above and try to save configuration to e.g. Downloads directory in the home folder.

**Comment by vikdevelop** [comment]
You can try to use another Flatpak app that allows saving files to your partition, and check if file will be saved or not.
