### ISSUE TITLE
feature_request: add a command line support to cleanup all config files so make the desktop to be the default settings

### ISSUE THREAD

**Issue by kamikaze211** [vikdevelop/SaveDesktop#254]
### The current problem or need

Sometime, some wrong settings (configuration files) may make our desktop environment keeping crash, black screen or freeze,etc.
So we need to switch to another TTY, and do something that make the DE settings to be the default ones.
If we have some backups, we can simply remove all the config files, or we can directly apply the settings of the backups.
So I think, if we can use one command to simply do that, it should be very nice.

### Describe the solution you'd like

I know a command line tool called [konsave], but it only supports KDE PLASMA.

**Comment by vikdevelop** [comment]
Hello, 
thank you for your feature request. 

This idea sounds pretty good. If a user imported a bad config file that caused them to destroy their desktop environment, they could restore it from another config file and have a working environment back. 

I will try to implement this to the next release version of the app.

**Comment by vikdevelop** [comment]
I released a new version that supports this feature. It is available to download in a few hours.

**Comment by kamikaze211** [comment]
> Hello, thank you for your feature request.
> 
> This idea sounds pretty good. If a user imported a bad config file that caused them to destroy their desktop environment, they could restore it from another config file and have a working environment back.
> 
> I will try to implement this to the next release version of the app.
> 
> EDIT: There is a small problem with DE recognition in tty, since no environment is defined in tty, so the desktop environment settings would not be imported, but icons, themes, fonts, Dconf settings and so on, would be imported.

Thank you very much, you did it so fast.
Appreciate for your good job.
I'd tested in terminal, but I found the help message of [SaveDesktop] doesn't contain the [--import-config] argument.

```
savedesktop --help
Arguments: 
 None | Run SaveDesktop app (GUI) 
 --background | Start periodic saving 
 --sync | Sync desktop configuration with other computer 
 --start-server | Start HTTP server for synchronization DE config with other computers 
 --help | Show this message
```

**Comment by vikdevelop** [comment]
For some unknown reason, the Flathub server did not update the app to the latest version, so the previous version, which does not have this feature, is still available.

**Comment by kamikaze211** [comment]
I'm using Archlinux, and I installed SaveDesktop from AUR.
Here is the package info:

The package that I installed on my system:
```
❯ paru -Qs savedesktop
local/savedesktop 3.2.2-1
    Save and load KDE Plasma, Xfce and GNOME-based DE configuration
```
The package that from the repo (AUR):
```
❯ paru -Si savedesktop
Repository      : aur
Name            : savedesktop
Version         : 3.2.2-1
Description     : Save and load KDE Plasma, Xfce and GNOME-based DE configuration
URL             : https://github.com/vikdevelop/SaveDesktop
AUR URL         : https://aur.archlinux.org/packages/savedesktop
Groups          : None
Licenses        : GPL-3.0-or-later
Provides        : None
Depends On      : hicolor-icon-theme  libadwaita  python-dbus  python-gobject
Make Deps       : git
Check Deps      : None
Optional Deps   : None
Conflicts With  : None
Maintainer      : yochananmarqos
Votes           : 1
Popularity      : 0.86812
First Submitted : Thu, 28 Dec 2023 01:38:05
Last Modified   : Mon, 15 Apr 2024 00:54:34
Out Of Date     : No
```
The CLI help message of the package:
```
❯ savedesktop --help
Arguments: 
 None | Run SaveDesktop app (GUI) 
 --background | Start periodic saving 
 --sync | Sync desktop configuration with other computer 
 --start-server | Start HTTP server for synchronization DE config with other computers 
 --help | Show this message
```
And there is no message if I use 'import-config' argument in terminal:
```
❯ savedesktop --import-config /home/ice/Downloads/SaveDesktop/archives/ice.sd.tar.gz
```

So I cannot confirm if I had installed the latest version, even it shows that the version is up-to-date.
And also I cannot check if the 'import-config' feature is working well.
May you add some words such as "successfully applied" to show after an 'import-config' command?

**Comment by vikdevelop** [comment]
Do you have installed version 3.2.2?
You can also try to use the native version, instructions are in the README.md of this repository.

**Comment by vikdevelop** [comment]
> May you add some words such as "successfully applied" to show after an 'import-config' command?
After importing configuration within this command, SaveDesktop displays message: "The configuration has been imported successfully!"

**Comment by kamikaze211** [comment]
> You can try to use the native version; instructions are in the README.md of this repository. Help message doesn't contain the --import-config argument, because the AUR package uses custom running script, see https://aur.archlinux.org/cgit/aur.git/tree/savedesktop.sh?h=savedesktop

Thank you very much.
I'll try to use the native version.
I found it works.
As a support for this project, I will help to translate the wiki and the newest words in the app from English to Chinese (Simple).
Have a good day.
Appreciate for your works.
