### ISSUE TITLE
feature_request: Support for COSMIC Desktop (Rust version)

### ISSUE THREAD

**Issue by onlyreportingissues** [vikdevelop/SaveDesktop#268]
### The current problem or need

COSMIC Desktop (Rust version) will release soon. The GNOME version of it will reach end of life soon. A pre-alpha can be installed already. I think it would be nice, if it could also be supported by this app.

### Describe the solution you'd like

Support for COSMIC Desktop (Rust version). Im sure that the COSMIC devs are willing to help with it, if requested.
You can find the project & the devs here https://github.com/pop-os/cosmic-epoch

**Comment by vikdevelop** [comment]
Hello,
thank you for your feature request.
I will try to implement support for the Rust version of the COSMIC environment in the next release version of the app.
