### ISSUE TITLE
feature_request: save from CLI

### ISSUE THREAD

**Issue by cheywood** [vikdevelop/SaveDesktop#272]
### The current problem or need

First, thanks for SaveDesktop :+1: :slightly_smiling_face: 

Have you considered exposing saving from the CLI interface?

### Describe the solution you'd like

To be able to save from the CLI, useful for integrating in scripts, custom schedules etc.

Existing configuration from the UI would be used, maybe taking the filename on the CLI?

Edit: typo

**Comment by vikdevelop** [comment]
Hello,
thank you for your feature request.

You can use the following command:
- if you are using Flatpak version of the app, use:
```
rm ~/.var/app/io.github.vikdevelop.SaveDesktop/data/periodic-saving.json && flatpak run io.github.vikdevelop.SaveDesktop --background
```
- if you are using Snap or native version of the app, use:
```
rm ~/.local/share/io.github.vikdevelop.SaveDesktop/periodic-saving.json && savedesktop --background
```
This command does the periodic saving from the parameters in the GUI. To make it work every time, set the app to periodic saving to "Daily".

**Comment by cheywood** [comment]
Brilliant, thanks for the quick response :+1:

So by setting the UI to does that mean this will also be running in the background (and create daily backups automatically)?

**Comment by vikdevelop** [comment]
Yes, if you set periodic saving as "Daily", SaveDesktop creates the backup file every day after logging in system or you can use command that I mentioned above. If you want, you can set another directory for the periodic saving file by clicking on the > button in the periodic saving row.

**Comment by cheywood** [comment]
Thanks again :smile:

I guess the feature request is to be able to generate a save from the CLI without getting any type of background process or scheduled backups involved; once the requested save is performed (presuming eg. the UI isn't launched) SaveDesktop wouldn't be active until triggered again.

It's just an idea, thought of as the matching pair for the `--import-config` you provide.

**Comment by vikdevelop** [comment]
I will try to implement this feature in the next version of the application. However, if you are interested in helping, you can open a pull request here on GitHub.

**Comment by cheywood** [comment]
> you can open a pull request

Ok, sure :+1:
