### ISSUE TITLE
bug: Starts saving but never stops and saves nothing

### ISSUE THREAD

**Issue by Free-Radical** [vikdevelop/SaveDesktop#279]
### Linux distribution

Fedora Linux 40.20240517.0 (Silverblue) x86_64

### Desktop Environment

GNOME

### Version of the SaveDesktop app

GNOME 46.1

### Package type

Flatpak from Flathub

### Bug description

Never able to save. says saving and keeps showing saving forever.

nothing saved no error messages

even tried -
`rm ~/.var/app/io.github.vikdevelop.SaveDesktop/data/periodic-saving.json && flatpak run io.github.vikdevelop.SaveDesktop --background`

**Comment by Free-Radical** [comment]
UPDATE-

```
→ flatpak run io.github.vikdevelop.SaveDesktop --background
saving settings from the Dconf database
saving Gtk settings
saving backgrounds
saving icons
saving themes
saving fonts
saving desktop folder
```

going on forever, letting it  run to see if it quits

**Comment by Free-Radical** [comment]
> 03:36:22  |base|khan@titan-prime ~ → Error copying directory /var/home/khan/.var/app/eu.betterbird.Betterbird: [('/var/home/khan/.var/app/eu.betterbird.Betterbird/.thunderbird/vyjafs1v.default-default/lock', '/var/home/khan/.var/app/io.github.vikdevelop.SaveDesktop/cache/tmp/periodic_saving/app/eu.betterbird.Betterbird/.thunderbird/vyjafs1v.default-default/lock', "[Errno 2] No such file or directory: '/var/home/khan/.var/app/eu.betterbird.Betterbird/.thunderbird/vyjafs1v.default-default/lock'")]
> Error copying directory /var/home/khan/.var/app/com.skype.Client: [('/var/home/khan/.var/app/com.skype.Client/config/skypeforlinux/SingletonLock', '/var/home/khan/.var/app/io.github.vikdevelop.SaveDesktop/cache/tmp/periodic_saving/app/com.skype.Client/config/skypeforlinux/SingletonLock', "[Errno 2] No such file or directory: '/var/home/khan/.var/app/com.skype.Client/config/skypeforlinux/SingletonLock'"), ('/var/home/khan/.var/app/com.skype.Client/config/skypeforlinux/SingletonSocket', '/var/home/khan/.var/app/io.github.vikdevelop.SaveDesktop/cache/tmp/periodic_saving/app/com.skype.Client/config/skypeforlinux/SingletonSocket', "[Errno 2] No such file or directory: '/var/home/khan/.var/app/com.skype.Client/config/skypeforlinux/SingletonSocket'"), ('/var/home/khan/.var/app/com.skype.Client/config/skypeforlinux/SingletonCookie', '/var/home/khan/.var/app/io.github.vikdevelop.SaveDesktop/cache/tmp/periodic_saving/app/com.skype.Client/config/skypeforlinux/SingletonCookie', "[Errno 2] No such file or directory: '/var/home/khan/.var/app/com.skype.Client/config/skypeforlinux/SingletonCookie'")]
> Error copying directory /var/home/khan/.var/app/org.torproject.torbrowser-launcher: [('/var/home/khan/.var/app/org.torproject.torbrowser-launcher/data/torbrowser/tbb/x86_64/tor-browser/Browser/TorBrowser/Data/Browser/profile.default/lock', '/var/home/khan/.var/app/io.github.vikdevelop.SaveDesktop/cache/tmp/periodic_saving/app/org.torproject.torbrowser-launcher/data/torbrowser/tbb/x86_64/tor-browser/Browser/TorBrowser/Data/Browser/profile.default/lock', "[Errno 2] No such file or directory: '/var/home/khan/.var/app/org.torproject.torbrowser-launcher/data/torbrowser/tbb/x86_64/tor-browser/Browser/TorBrowser/Data/Browser/profile.default/lock'")]
> ^C
> 03:37:09  |base|khan@titan-prime ~ → 
> 03:37:52  |base|khan@titan-prime ~ → Error copying directory /var/home/khan/.var/app/io.github.mimbrero.WhatsAppDesktop: [('/var/home/khan/.var/app/io.github.mimbrero.WhatsAppDesktop/config/whatsapp-desktop-linux/SingletonLock', '/var/home/khan/.var/app/io.github.vikdevelop.SaveDesktop/cache/tmp/periodic_saving/app/io.github.mimbrero.WhatsAppDesktop/config/whatsapp-desktop-linux/SingletonLock', "[Errno 2] No such file or directory: '/var/home/khan/.var/app/io.github.mimbrero.WhatsAppDesktop/config/whatsapp-desktop-linux/SingletonLock'"), ('/var/home/khan/.var/app/io.github.mimbrero.WhatsAppDesktop/config/whatsapp-desktop-linux/SingletonSocket', '/var/home/khan/.var/app/io.github.vikdevelop.SaveDesktop/cache/tmp/periodic_saving/app/io.github.mimbrero.WhatsAppDesktop/config/whatsapp-desktop-linux/SingletonSocket', "[Errno 2] No such file or directory: '/var/home/khan/.var/app/io.github.mimbrero.WhatsAppDesktop/config/whatsapp-desktop-linux/SingletonSocket'"), ('/var/home/khan/.var/app/io.github.mimbrero.WhatsAppDesktop/config/whatsapp-desktop-linux/SingletonCookie', '/var/home/khan/.var/app/io.github.vikdevelop.SaveDesktop/cache/tmp/periodic_saving/app/io.github.mimbrero.WhatsAppDesktop/config/whatsapp-desktop-linux/SingletonCookie', "[Errno 2] No such file or directory: '/var/home/khan/.var/app/io.github.mimbrero.WhatsAppDesktop/config/whatsapp-desktop-linux/SingletonCookie'")]
> Error copying directory /var/home/khan/.var/app/us.zoom.Zoom: [('/var/home/khan/.var/app/us.zoom.Zoom/.zoom/data/com.zoom.ipc.assistantapp__res', '/var/home/khan/.var/app/io.github.vikdevelop.SaveDesktop/cache/tmp/periodic_saving/app/us.zoom.Zoom/.zoom/data/com.zoom.ipc.assistantapp__res', '`/var/home/khan/.var/app/us.zoom.Zoom/.zoom/data/com.zoom.ipc.assistantapp__res` is a named pipe'), ('/var/home/khan/.var/app/us.zoom.Zoom/.zoom/data/com.zoom.ipc.assistantapp__req', '/var/home/khan/.var/app/io.github.vikdevelop.SaveDesktop/cache/tmp/periodic_saving/app/us.zoom.Zoom/.zoom/data/com.zoom.ipc.assistantapp__req', '`/var/home/khan/.var/app/us.zoom.Zoom/.zoom/data/com.zoom.ipc.assistantapp__req` is a named pipe'), ('/var/home/khan/.var/app/us.zoom.Zoom/.zoom/data/com.zoom.ipc.additional_assistantapp__res', '/var/home/khan/.var/app/io.github.vikdevelop.SaveDesktop/cache/tmp/periodic_saving/app/us.zoom.Zoom/.zoom/data/com.zoom.ipc.additional_assistantapp__res', '`/var/home/khan/.var/app/us.zoom.Zoom/.zoom/data/com.zoom.ipc.additional_assistantapp__res` is a named pipe'), ('/var/home/khan/.var/app/us.zoom.Zoom/.zoom/data/com.zoom.ipc.additional_assistantapp__req', '/var/home/khan/.var/app/io.github.vikdevelop.SaveDesktop/cache/tmp/periodic_saving/app/us.zoom.Zoom/.zoom/data/com.zoom.ipc.additional_assistantapp__req', '`/var/home/khan/.var/app/us.zoom.Zoom/.zoom/data/com.zoom.ipc.additional_assistantapp__req` is a named pipe')]
> Error copying directory /var/home/khan/.var/app/io.github.ungoogled_software.ungoogled_chromium: [('/var/home/khan/.var/app/io.github.ungoogled_software.ungoogled_chromium/config/chromium/SingletonLock', '/var/home/khan/.var/app/io.github.vikdevelop.SaveDesktop/cache/tmp/periodic_saving/app/io.github.ungoogled_software.ungoogled_chromium/config/chromium/SingletonLock', "[Errno 2] No such file or directory: '/var/home/khan/.var/app/io.github.ungoogled_software.ungoogled_chromium/config/chromium/SingletonLock'"), ('/var/home/khan/.var/app/io.github.ungoogled_software.ungoogled_chromium/config/chromium/SingletonSocket', '/var/home/khan/.var/app/io.github.vikdevelop.SaveDesktop/cache/tmp/periodic_saving/app/io.github.ungoogled_software.ungoogled_chromium/config/chromium/SingletonSocket', "[Errno 2] No such file or directory: '/var/home/khan/.var/app/io.github.ungoogled_software.ungoogled_chromium/config/chromium/SingletonSocket'"), ('/var/home/khan/.var/app/io.github.ungoogled_software.ungoogled_chromium/config/chromium/SingletonCookie', '/var/home/khan/.var/app/io.github.vikdevelop.SaveDesktop/cache/tmp/periodic_saving/app/io.github.ungoogled_software.ungoogled_chromium/config/chromium/SingletonCookie', "[Errno 2] No such file or directory: '/var/home/khan/.var/app/io.github.ungoogled_software.ungoogled_chromium/config/chromium/SingletonCookie'")]
> Error copying directory /var/home/khan/.var/app/org.mozilla.firefox: [('/var/home/khan/.var/app/org.mozilla.firefox/cache/mozilla/firefox/cy8z7vi8.default-release/cache2/entries/D3E110A15F1B71A58D6A4A47BD3B2C7106D5DC05', '/var/home/khan/.var/app/io.github.vikdevelop.SaveDesktop/cache/tmp/periodic_saving/app/org.mozilla.firefox/cache/mozilla/firefox/cy8z7vi8.default-release/cache2/entries/D3E110A15F1B71A58D6A4A47BD3B2C7106D5DC05', "[Errno 2] No such file or directory: '/var/home/khan/.var/app/org.mozilla.firefox/cache/mozilla/firefox/cy8z7vi8.default-release/cache2/entries/D3E110A15F1B71A58D6A4A47BD3B2C7106D5DC05'"), ('/var/home/khan/.var/app/org.mozilla.firefox/cache/mozilla/firefox/cy8z7vi8.default-release/cache2/entries/A186AEFC2E8A4AB0AD2E487B8468D35EB613E856', '/var/home/khan/.var/app/io.github.vikdevelop.SaveDesktop/cache/tmp/periodic_saving/app/org.mozilla.firefox/cache/mozilla/firefox/cy8z7vi8.default-release/cache2/entries/A186AEFC2E8A4AB0AD2E487B8468D35EB613E856', "[Errno 2] No such file or directory: '/var/home/khan/.var/app/org.mozilla.firefox/cache/mozilla/firefox/cy8z7vi8.default-release/cache2/entries/A186AEFC2E8A4AB0AD2E487B8468D35EB613E856'"), ('/var/home/khan/.var/app/org.mozilla.firefox/.mozilla/firefox/cy8z7vi8.default-release/lock', '/var/home/khan/.var/app/io.github.vikdevelop.SaveDesktop/cache/tmp/periodic_saving/app/org.mozilla.firefox/.mozilla/firefox/cy8z7vi8.default-release/lock', "[Errno 2] No such file or directory: '/var/home/khan/.var/app/org.mozilla.firefox/.mozilla/firefox/cy8z7vi8.default-release/lock'")]
> saving desktop environment configuration files
> cp: cannot stat '/var/home/khan/.local/share/gnome-background-properties': No such file or directory
> creating configuration archive
> tar: .: file changed as we read it
> moving the configuration archive to the user-defined directory
> Configuration saved.
> \
> [1]+  Done                    flatpak run io.github.vikdevelop.SaveDesktop --background
> > "
> > ^C
> 06:52:52  |base|khan@titan-prime ~ → 


took over 3 hours

**Comment by Free-Radical** [comment]
Created a 24 GB file!

Latest_configuration.sd.tar.gz

**Comment by vikdevelop** [comment]
Hello,
I tested on Fedora Workstation 40, and I did not have the above problems.
Please be sure if your desktop folder or your Flatpak apps data is not too big...

**Comment by Free-Radical** [comment]
Thanks, but I have no idea what the size of the data is.
Can u pls tell me how to calc it?

FYI SaveDekstop file without Flatpaks works well and is 1.5Gb vs 22.3 Gb with Flatpaks.

Keep in mind a LOT of new immmutable distros want us to mostly use Flatpak like packages

PS I had a question, How can I keep the state of 2  desktops synced? (sorta like Apple Continuity feature)  E.g. i'm working on my desktop , than I  start working on my Laptop, but when i start my laptop I am able to recreate the Desktop state that mirrors the last state of the Desktop, can this be done (not using RDP etc) but an actual DE state sync? Would appreciate any ideas/leads. THANKS!

**Comment by vikdevelop** [comment]
I'll take it one at a time:

1) You can use the Flatpak apps data selection feature in the app to select what specific Flatpak app data will be saved or not. It helps to reduce the size of the archive. 

    To set up this, click on the "Items to include in the configuration archive" row at the Save page, then click on the Flatpak apps row and enable the "User data of installed Flatpak apps", and then on the ">" button.

2) Yes, SaveDesktop allows you to sync your desktop environment configuration between computers on the local network. More information is available [here](https://github.com/vikdevelop/SaveDesktop/wiki/Synchronization-between-computers-in-the-network).

**Comment by Free-Radical** [comment]
> 2\. Yes, SaveDesktop allows you to sync your desktop environment configuration between computers on the local network. More information is available [here](https://github.com/vikdevelop/SaveDesktop/wiki/Synchronization-between-computers-in-the-network).

Hmm, Perhaps I'm doing something wrong, but its not working the way i specified. As I said want to **move from desktop 1 to desktop 2, and have all the same open windows etc open up  on desktop 2 when I login or click restore desktop from SAVEDESKTOP. That doesnt happen.** Seems all desktop _settings_ are imported , but the state of the last desktop does not popup.
By "state" I mean:  what windows were open, their locations in the desktop,  what they were showing, etc

If savedesktop doesn't do this, is it possible to do this? is there a program that can do this or part of it?

THANKS

**Comment by vikdevelop** [comment]
I haven't found anything like this for Linux, but you can use some remote desktop control tools like AnyDesk.
