### ISSUE TITLE
bug: SaveDesktop doesn't save properly when a folder has a name with spaces

### ISSUE THREAD

**Issue by ENTPRESTIGIOUS** [vikdevelop/SaveDesktop#287]
### Linux distribution

OpenSUSE TumbleWeed 20240625

### Desktop Environment

KDE Plasma

### Version of the SaveDesktop app

3.3

### Package type

Flatpak from Flathub

### Bug description

When I save to a directory that has a space in the folder name "Back Ups" instead of "Backups", SaveDesktop says it saved but saves nothing.

**Comment by vikdevelop** [comment]
Hello, is it a problem to store configurations in folders without spaces?

**Comment by vikdevelop** [comment]
Hello, so I in the end decided to add support for saving and importing configuration to or from folders with spaces. This small fix will be included in the next version of the app, which is `3.3.1`. Although I personally don't have folders with spaces, but I understand that some people are used to it.

**Comment by ENTPRESTIGIOUS** [comment]
> Hello, so I in the end decided to add support for saving and importing configuration to or from folders with spaces. This small fix will be included in the next version of the app, which is `3.3.1`. Although I personally don't have folders with spaces, but I understand that some people are used to it.

Thank you very much!
