### ISSUE TITLE
question: I'm not sure if an internet connection is really necessary

### ISSUE THREAD

**Issue by BAleex** [vikdevelop/SaveDesktop#293]
### Your question

Hi,
I tried to start the program, but it didn't work. I tried it later when I had Internet and started the program. After some trial and error, I found out that it was really due to the lack of an Internet connection that the program would not start. However, it is completely unclear to me why this program needs an Internet connection?
I use the Flatpak-Editioin under Fedora Workstation 39, all packages are up to date.
Many thanks and best regards 
Alex

**Comment by vikdevelop** [comment]
Hello, the application requires an internet connection for synchronization between computers. When loading the app, it detects the IP address of your device. If you are not connected to the internet, SaveDesktop is not launched. 

I understand that you are not always connected to the internet. So I will try to fix it in the next micro version that will be 3.3.1.
