### ISSUE TITLE
feature_request: support file based sync

### ISSUE THREAD

**Issue by 13hannes11** [vikdevelop/SaveDesktop#297]
### The current problem or need

I usually do not use my computers at the same time so setting up sync does does not really work well for me.

### Describe the solution you'd like

The best option would be to be able to periodically sync with a file. This way I could use Nextcloud to handle the transfer of the sync file.

**Comment by vikdevelop** [comment]
Hello, thank you for your feature request. Do you mean, like, to be able to select the cloud as the location to store the periodic storage file, and then use a web link to that periodic storage file located somewhere on the cloud as the URL for synchronization?

**Comment by 13hannes11** [comment]
I was thinking more of a file that I can synchronise  using another application.

For example I could have Dropbox installed on two devices and then making changes on one updates the file. The application on the other computer would detect that the file has changed and update the local configuration (such as installed apps)

So in effect I would like support to synchronise with a file where the file itself is being watched for changes and updated with any local changes.

I hope that what I am writing makes any sense 😀

**Comment by vikdevelop** [comment]
I am afraid so this feature will be arduous to implement this feature. I don't use cloud on my computer.

However, I'm not opposed to a pull request from the community. So I will mark this issue with "good first issue" label.

**Comment by vikdevelop** [comment]
I am afraid, so it will be arduous to implement this feature. I don't use the cloud on my computer.

However, I'm not opposed to a pull request from the community. So I will mark this issue with the "good first issue" label.

**Comment by 13hannes11** [comment]
You as the maintainer are the one who decides what to work on so I fully understand if you personally do not see this as a priority. I'm glad that you are open to this being added via a PR.

**Comment by vikdevelop** [comment]
So I tried to do it in my spare time and released a beta edition. There are instructions on how to test it in the Github release, it's simple and I'd be happy if you test it and let me know what you think.

**Comment by vikdevelop** [comment]
So I tried to do it in my spare time and released a beta release. There are instructions on how to test it in the Github release, it's simple and I'd be happy if you test it and let me know what you think.
