### ISSUE TITLE
bug:unable to connect sync to another computer connection refused

### ISSUE THREAD

**Issue by zany130** [vikdevelop/SaveDesktop#312]
### Linux distribution

Bazzite

### Desktop Environment

KDE Plasma

### Version of the SaveDesktop app

3.3.2

### Package type

Flatpak from Flathub

### Bug description

with both systems running bazzite and the same save desktop flatpak

1. on system 1 go to the sync tab
2. click set up the sync file
3. On system 2 go to the sync tab
4.  On system 2 select connect with other computer
5.  On system 2 enter URL as shown on System 1 
6. See `error urlopen error [Errno 111] Connection refused`

terminal output on system 2 (system 1 has the same output minus the traceback part)

```
flatpak run --branch=stable --arch=x86_64 --command=run.sh io.github.vikdevelop.SaveDesktop

(main_window.py:3): Adwaita-WARNING **: 19:54:03.300: Using GtkSettings:gtk-application-prefer-dark-theme with libadwaita is unsupported. Please use AdwStyleManager:color-scheme instead.
/app/main_window.py:232: DeprecationWarning: Adw.ViewSwitcherTitle.set_stack is deprecated
  self.switcher_title.set_stack(self.stack)
/app/main_window.py:233: DeprecationWarning: Adw.ViewSwitcherTitle.set_title is deprecated
  self.switcher_title.set_title("")
/app/main_window.py:810: DeprecationWarning: Gtk.Widget.get_style_context is deprecated
  self.setdBox.get_style_context().add_class(class_name='boxed-list')
/app/main_window.py:810: DeprecationWarning: Gtk.StyleContext.add_class is deprecated
  self.setdBox.get_style_context().add_class(class_name='boxed-list')
/app/main_window.py:869: DeprecationWarning: Gtk.Widget.show is deprecated
  self.setDialog.show()
False
Traceback (most recent call last):
  File "/app/main_window.py", line 900, in urlDialog_closed
    if jS["periodic-import"] == "Manually2":
       ^^
UnboundLocalError: cannot access local variable 'jS' where it is not associated with a value
```

**Comment by vikdevelop** [comment]
Hello,
please ensure that you have selected the periodic saving file and periodic synchronization interval in the "Set up the sync file" dialog. After closing the dialog, log out of the system on the first computer, and on the second computer, enter the URL from the first computer.

In the 3.4 version, which is in beta testing, the setting up the synchronization is simpler, and also you can also use the cloud drive folder instead of a URL. The instructions are [here](https://github.com/vikdevelop/SaveDesktop/discussions/303).

**Comment by vikdevelop** [comment]
Hello,
please ensure that you have selected the periodic saving file and periodic synchronization interval in the "Set up the sync file" dialog. After closing the dialog, log out of the system on the first computer, and on the second computer, enter the URL from the first computer.

In the 3.4 version, which is in beta testing, the setting up the synchronization is simpler, and you can also use the cloud drive folder instead of a URL. The instructions are [here](https://github.com/vikdevelop/SaveDesktop/discussions/303).

**Comment by zany130** [comment]
forgot to mention that I did setup a saving file and sync interval.

Still getting the same connection refused

on bazzite you can't "log out". "logging out" just log you into steam game mode. there is no login manager  (the same as a steam deck)

**Comment by vikdevelop** [comment]
> on bazzite you can't "log out". "logging out" just log you into steam game mode. there is no login manager (the same as a steam deck)

In that case, restart the device instead of logging out. After that, SaveDesktop starts the HTTP server that shares the periodic saving file on the network. But, if you still have problems setting up the synchronization, start the HTTP server by using this command in the terminal: 
```
flatpak run io.github.vikdevelop.SaveDesktop --start-server
```

**Comment by vikdevelop** [comment]
> on bazzite you can't "log out". "logging out" just log you into steam game mode. there is no login manager (the same as a steam deck)

In that case, restart the device instead of logging out. After that, SaveDesktop starts the HTTP server that shares the periodic saving file on the network. But, if you still have problems setting up the synchronization, start the HTTP server by using this command in the terminal: 
```
flatpak run io.github.vikdevelop.SaveDesktop --start-server
```

**Comment by zany130** [comment]
hmm, for some reason, system 2 just freezes now when entering the URL for system one and hitting apply
and I don't see anything in the terminal just 

```
flatpak run --branch=stable --arch=x86_64 --command=run.sh io.github.vikdevelop.SaveDesktop

(main_window.py:3): Adwaita-WARNING **: 19:54:03.300: Using GtkSettings:gtk-application-prefer-dark-theme with libadwaita is unsupported. Please use AdwStyleManager:color-scheme instead.
/app/main_window.py:232: DeprecationWarning: Adw.ViewSwitcherTitle.set_stack is deprecated
  self.switcher_title.set_stack(self.stack)
/app/main_window.py:233: DeprecationWarning: Adw.ViewSwitcherTitle.set_title is deprecated
  self.switcher_title.set_title("")
/app/main_window.py:810: DeprecationWarning: Gtk.Widget.get_style_context is deprecated
  self.setdBox.get_style_context().add_class(class_name='boxed-list')
/app/main_window.py:810: DeprecationWarning: Gtk.StyleContext.add_class is deprecated
  self.setdBox.get_style_context().add_class(class_name='boxed-list')
/app/main_window.py:869: DeprecationWarning: Gtk.Widget.show is deprecated
  self.setDialog.show()
  ```

**Comment by zany130** [comment]
I figured it out it was an issue with my postmaster firewall. Disabling it fixes it. 


Unfortunately, Postmaster sees the HTTP server as running from a Python command and not from the Save Desktop flatpack, so my rules of allowing everything for the Save Desktop app don't apply.

I had to allow incoming connections from all python processes
