### ISSUE TITLE
Run without flatpak

### ISSUE THREAD

**Issue by hightowe** [vikdevelop/SaveDesktop#33]
It would be very nice to be able to run this program without flatpak.

For a sense of why, see this (the 1.3GB of dependencies):

~~~
# I installed with:
# $ flatpak remote-add --if-not-exists --user flathub https://dl.flathub.org/repo/flathub.flatpakrepo
# $ flatpak install --user SaveDesktop

# I considered this to be insane:
# $ du -sh /home/hightowe/.local/share/flatpak
# 1.3G  /home/hightowe/.local/share/flatpak

# I then uninstalled with:
# $ flatpak uninstall --user SaveDesktop
# $ flatpak uninstall --user --unused
# $ du -sh /home/hightowe/.local/share/flatpak
# 3.5M  /home/hightowe/.local/share/flatpak
~~~

I have all of the requisite dependencies install in my OS for SaveDesktop to run, but as best I can tell the code assumes that it must be run from flatpak. If I am incorrect, I apologize and would appreciate a lesson in how to run without flatpak.

~~~
~/bin/SaveDesktop-1.8.1 $ python3 ./src/main_window.py 
Traceback (most recent call last):
  File "/home/hightowe/bin/SaveDesktop-1.8.1/./src/main_window.py", line 54, in <module>
    locale = open(f"/app/translations/{lang}")
FileNotFoundError: [Errno 2] No such file or directory: '/app/translations/en.json'
~~~

Thanks.

**Comment by timur-g** [comment]
Please consider to provide direct install. With simple script we can update repo and build. I do not have flatpaks.

**Comment by timur-g** [comment]
Thanks, that was it. 
I see it requires GTK4 so this way would not work in may case of LinuxMint 21 which has GTK3. I understand this is Flatpack for.
Still, wonder if there is a reason to force version GTK4.

**Comment by timur-g** [comment]
> Out of curiosity — is there a specific reason you prefer not to use Flatpak?

I'm somewhat conservative user, prefer DEBs where I can have them and I mostly use PPAs and can fit almost all together. 
Never so far had need for Flatpak, this would be the first time I cannot use PPA or local build. In that case I may try Flatpak, where size concerns me, as disk space is running out fast.
So I am open to that, unlike Snaps which I do not want at all, and Linux Mint does not have them preinstalled.
