### ISSUE TITLE
Issue while creating snap for this app

### ISSUE THREAD

**Issue by soumyaDghosh** [vikdevelop/SaveDesktop#35]
I found out that you've hard-coded the paths, only for flatpak. So, the snap is not able to find the path. Can you do some change in it? Or can you just locate where and in which places they are hard-coded? So, that I can change them.

**Comment by soumyaDghosh** [comment]
Well, the main is the `/app`, I have changed it to the necessary folders, and the app is ready. I just need to test properly now.

**Comment by soumyaDghosh** [comment]
Things doesn't seem to be working on Ubuntu. I mostly don't customize things. But, I installed `papirus-icon` and changed to a local wallpaper. Then I backupped the configs and reverted to the original one. Then imported the config file, but nothing changed. Though I guess things copied properly. Any thoughts, how to debug, what log should I give?

**Comment by soumyaDghosh** [comment]
It's the snap

**Comment by vikdevelop** [comment]
I've never done Snap. I've only done Flatpak. But maybe I need to set stricter permissions (confinement) in the snapcraft.yml manifest. I don't know.

**Comment by soumyaDghosh** [comment]
Do you have a `snapcraft.yaml`? The thing is, I guess the main issue here is your hard-coded paths. And as I don't undertstand the python language well, I am not able to make up things properly

**Comment by vikdevelop** [comment]
I created Snap of this app. It is available on the Snap store (currently in the edge version): https://snapcraft.io/savedesktop-vikdevelop

**Comment by soumyaDghosh** [comment]
Hii.. @vikdevelop please, don't use a duplicate name. I have the name registered. Kindly give me your mail id, I'll add you as a collaborator and then I will transfer the snap to you.

**Comment by vikdevelop** [comment]
The email is: super-vik1@protonmail.com
