### ISSUE TITLE
feature_request: Remember and restore positions of backed up icons 

### ISSUE THREAD

**Issue by true911m** [vikdevelop/SaveDesktop#350]
### The current problem or need

I found SaveDesktop while looking for a linux equivalent to a Windows app I've used for years.  I would like it to be able to restore my desktop icons into the same positions and layout that I had them placed when I backed them up.

### Describe the solution you'd like

I asked about this in a Linux Mint forum thread at https://forums.linuxmint.com/posting.php?mode=quote&p=2553192.  User smurphos responded with a developer's perspective about some possible solutions, and I'd like you to take a look to see if they're feasible to achieve this goal.

**Comment by vikdevelop** [comment]
Hello,
thank you for your feature request, and I apologize for the late response.
I will add this feature in the next micro version, which is 3.5.1. It is just adding the `~/.local/share/gvfs-metadata` folder, so it is not a problem.

**Comment by true911m** [comment]
Awesome, thank you!
__________________________________________________

*Mark ***@***.***
