### ISSUE TITLE
bug:Periodical sync doesn't work

### ISSUE THREAD

**Issue by proninyaroslav** [vikdevelop/SaveDesktop#352]
### Linux distribution

Fedora 41

### Desktop Environment

GNOME

### Version of the SaveDesktop app

3.5

### Package type

Flatpak from Flathub

### Bug description

To set up a periodic sync between two machines, I set it up using the instructions on the app's website, except that I disabled bidirectional sync. Syncing only happens the first time I configure the first machine's save file on my Nextcloud server, and when I select that file on the second machine. I can tell by the fact that after a week (the sync interval I chose), the file's modification date and content are not updated, and the configuration on the second machine is not updated either.

**Comment by vikdevelop** [comment]
Hello, open the Terminal app and enter this command:
flatpak run io.github.vikdevelop.SaveDesktop --sync
Then, insert the output here.

If you get something like "The configuration has already been imported today." use this command: 
rm ~/.var/app/io.github.vikdevelop.SaveDesktop/data/sync-info.json
and run the first mentioned command again.

**Comment by vikdevelop** [comment]
Have you tried it on the first or the second computer? If you tried it on the second computer, open the SaveDesktop app from the terminal using this command:
flatpak run io.github.vikdevelop.SaveDesktop
Press the Ctrl+Shift+C keyboard shortcut or go to the Sync page and click on the "Connect to the cloud storage" button. Select "Manually" as the periodic synchronization interval and click on the Sync button in the application menu by clicking on the three dots. And insert the output here, of course.

**Comment by vikdevelop** [comment]
You can also try to create the periodic saving file on the first computer by using this command:
flatpak run io.github.vikdevelop.SaveDesktop --save-now

**Comment by proninyaroslav** [comment]
The saving file exists. At that moment the network drive wasn't mounted, now I mounted it, but it didn't change anything. As I understand it, the app should do it itself in any case.

**Comment by vikdevelop** [comment]
The application should use the bash script, that runs after login to the system and which mounts the cloud drive, syncs the configuration and saves it periodically, and optionally, installs the Flatpak apps and their data.

The script is located in the data folder of the app, so you can run it on the second computer by using this command and check if the synchronization works or not:
sh ~/.var/app/io.github.vikdevelop.SaveDesktop/data/savedesktop-synchronization.sh
and insert the output here.

**Comment by proninyaroslav** [comment]
No such file

**Comment by vikdevelop** [comment]
Then, set up synchronization on the second computer again. Open the app, go to the Sync page and then click on the "Connect to the cloud storage" button and select your Nextcloud storage connected via GNOME Online Accounts as a cloud drive folder. If you don't setup this, the savedesktop-synchronization.sh will not be created.

**Comment by proninyaroslav** [comment]
Before I opened Issue, I did it again and setup the synchronization from beginning.

**Comment by vikdevelop** [comment]
On the first computer, open the same page and click on the "Set up the sync file". Select your Nextcloud storage connected via GNOME Online Accounts as a peeiodic saving folder.

**Comment by proninyaroslav** [comment]
Ok. By the way the second script is present (flatlak install script).

**Comment by proninyaroslav** [comment]
So, I clean all the old app data and repeated the steps. On the first PC, the script `periodic-saving.json` appeared and the shortcut "peoridic backups" appeared in autorun, on the second PC, the `data` folder is empty, although the shortcuts "synchronization" and "flatpak apps installer" are in autorun.

**Comment by vikdevelop** [comment]
Open the app on anything computer from Terminal, go to the Sync page, click on the "Set up the sync file" or "Connect to the cloud storage" button on that page, and then click on the Apply button. Insert the output here.

**Comment by proninyaroslav** [comment]
On the first:

```
Failed to extract the necessary values to set up automatic cloud storage connection after logging into the system.
Exception in thread Thread-3 (save_file):
Traceback (most recent call last):
  File "/usr/lib/python3.12/threading.py", line 1075, in _bootstrap_inner
    self.run()
  File "/usr/lib/python3.12/threading.py", line 1012, in run
    self._target(*self._args, **self._kwargs)
  File "/app/main_window.py", line 650, in save_file
    self.set_up_auto_mount()
  File "/app/main_window.py", line 885, in set_up_auto_mount
    synchronization_content = f'#!/usr/bin/bash\n{cmd}\nsleep 60s\n{sync_cmd}\n{periodic_saving_cmd}'
                                                  ^^^
UnboundLocalError: cannot access local variable 'cmd' where it is not associated with a value
```

**Comment by vikdevelop** [comment]
It looks like the SaveDesktop app can not get the necessary values from the selected folder. In which format is the periodic saving folder?
Good formats are: `/run/user/1000/gvfs/onedrive:host=cb2e912317ff9f2f/OneDrive/` (for OneDrive( or `/run/user/1000/gvfs/google-drive:host=gmail.com?user=username/9PiKWj45A` (for Google Drive)

**Comment by vikdevelop** [comment]
It looks like the SaveDesktop app can not get the necessary values from the selected folder. What does your periodic saving folder look like?
For example, in the OneDrive case, the periodic saving folder looks like this: `/run/user/1000/gvfs/onedrive:host=cb2e912317ff9f2f/OneDrive/` or in the Google Drive case: `/run/user/1000/gvfs/google-drive:host=gmail.com?user=username/9PiKWj45A`

**Comment by proninyaroslav** [comment]
Nextcloud: `/run/user/1000/gvfs/dav:host=mydomain.com,ssl=true,user=admin,prefix=%2Fremote.php%2Fwebdav/nas/backup/SaveDesktop/Latest_configuration.sd.tar.gz`

**Comment by proninyaroslav** [comment]
Moreover, it successfully creates a synchronization file.

**Comment by vikdevelop** [comment]
I released the `3.5-beta_2024-12-17` version, which should fix this bug. You can try it by installing the app from the Flathub Beta repository (instructions [here](https://github.com/vikdevelop/SaveDesktop?tab=readme-ov-file#1-flathub-beta)), but you need to remove the stable version before installing for the directory permissions to work properly, or **by installing the native version using these commands:**
```bash
git clone https://github.com/vikdevelop/SaveDesktop --branch=fix-nextcloud && cd SaveDesktop && sh native/directories.sh --install
```
(if you would then want to remove SaveDesktop native version and leave the Flatpak version, you can use: `cd SaveDesktop && sh native/directories.sh --remove`)

Let me know if it works or not.

**Comment by proninyaroslav** [comment]
The setup on the first PC seemed to go smoothly, although I didn't look at the log at that moment. But there are some problems on the second PC. When I connected the cloud storage, it didn't do any synchronization, the data folder was empty, but the shortcuts were present in the startup. I decided to do the synchronization manually, with the argument `--sync`. The first launch caused this error (I enabled bidirectioanl synchronization on the second PC), the disk was not mounted. I mounted it manually, then unmounted it, and started the synchronization again. This time the disk was mounted and synchronization was successful.

```
Saving immediately
saving settings from the Dconf database
saving Gtk settings
saving backgrounds
saving icons
saving themes
cp: не удалось выполнить stat для '/home/yaroslav/.local/share/themes': Нет такого файла или каталога
saving fonts
saving list of installed Flatpak apps
ls: невозможно получить доступ к '/home/yaroslav/.local/share/flatpak/app': Нет такого файла или каталога
saving desktop environment configuration files
cp: не удалось выполнить stat для '/home/yaroslav/.local/share/gnome-background-properties': Нет такого файла или каталога
creating the configuration archive
tar: .: файл изменился во время чтения
moving the configuration archive to the user-defined directory
Configuration saved.
Traceback (most recent call last):
  File "/app/bin/savedesktop", line 35, in <module>
    from network_sharing import Syncing
  File "/app/network_sharing.py", line 132, in <module>
    Syncing()
  File "/app/network_sharing.py", line 18, in __init__
    self.get_sync_interval()
  File "/app/network_sharing.py", line 27, in get_sync_interval
    self.check_sync_date()
  File "/app/network_sharing.py", line 67, in check_sync_date
    self.download_config()
  File "/app/network_sharing.py", line 76, in download_config
    self.get_pb_info()
  File "/app/network_sharing.py", line 101, in get_pb_info
    with open(os.path.join(settings['file-for-syncing'], "SaveDesktop.json")) as data:
         ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
FileNotFoundError: [Errno 2] No such file or directory: '/run/user/1000/gvfs/dav:host=cloud.proninyaroslav.ru,ssl=true,user=admin,prefix=%2Fremote.php%2Fwebdav/nas/backup/SaveDesktop/SaveDesktop.json'
```

Then I unmounted the disk, deleted the sync file and ran the app again, but this time it didn't mount the disk automatically anymore, it gave me an error again and I had to mount it manually

```
moving the configuration archive to the user-defined directory
Traceback (most recent call last):
  File "/app/periodic_saving.py", line 129, in <module>
    pb.run(args.now)
  File "/app/periodic_saving.py", line 31, in run
    self.backup()
  File "/app/periodic_saving.py", line 104, in backup
    shutil.copyfile('cfg.sd.tar.gz', f'{self.pbfolder}/{filename}.sd.tar.gz')
  File "/usr/lib/python3.12/shutil.py", line 262, in copyfile
    with open(dst, 'wb') as fdst:
         ^^^^^^^^^^^^^^^
FileNotFoundError: [Errno 2] No such file or directory: '/run/user/1000/gvfs/dav:host=cloud.proninyaroslav.ru,ssl=true,user=admin,prefix=%2Fremote.php%2Fwebdav/nas/backup/SaveDesktop/Latest_configuration.sd.tar.gz'
Traceback (most recent call last):
  File "/app/bin/savedesktop", line 35, in <module>
    from network_sharing import Syncing
  File "/app/network_sharing.py", line 132, in <module>
    Syncing()
  File "/app/network_sharing.py", line 18, in __init__
    self.get_sync_interval()
  File "/app/network_sharing.py", line 27, in get_sync_interval
    self.check_sync_date()
  File "/app/network_sharing.py", line 67, in check_sync_date
    self.download_config()
  File "/app/network_sharing.py", line 75, in download_config
    subprocess.run(['python3', f'{system_dir}/periodic_saving.py', '--now'], check=True)
  File "/usr/lib/python3.12/subprocess.py", line 571, in run
    raise CalledProcessError(retcode, process.args,
subprocess.CalledProcessError: Command '['python3', '/app/periodic_saving.py', '--now']' returned non-zero exit status 1.
```

**Comment by vikdevelop** [comment]
> Open the app on anything computer from Terminal, go to the Sync page, click on the "Set up the sync file" or "Connect to the cloud storage" button on that page, and then click on the Apply button. Insert the output here.

Follow these previous steps. It looks like, the app still can't get the necessary variables from the GVFS folder as your drive is not automatically mounted at the synchronization time, based on your outputs.

**Comment by proninyaroslav** [comment]
```
Failed to extract the necessary values to set up automatic cloud storage connection after logging into the system.
Traceback (most recent call last):
  File "/app/main_window.py", line 754, in cloudDialog_closed
    self.set_up_auto_mount()
  File "/app/main_window.py", line 885, in set_up_auto_mount
    synchronization_content = f'#!/usr/bin/bash\n{cmd}\nsleep 60s\n{sync_cmd}\n{periodic_saving_cmd}'
                                                  ^^^
UnboundLocalError: cannot access local variable 'cmd' where it is not associated with a value
```

**Comment by vikdevelop** [comment]
Do you really have the `3.5-beta_2024-12-17` version (in the About app dialog)?

**Comment by vikdevelop** [comment]
I found out that changes on Flathub have not taken effect, so the updated build will be available in a few hours. You can also try the native version above instead of Flathub.

**Comment by proninyaroslav** [comment]
Ok I can wait flathub

**Comment by proninyaroslav** [comment]
So, on the beta:

The first PC gives me this errors:

```
Configuration saved.
/app/main_window.py:580: Warning: corrupted double-linked list detected
  self.file_row.set_subtitle(f'{settings["periodic-saving-folder"]}/{settings["filename-format"]}.sd.tar.gz')
/usr/lib/python3.12/site-packages/gi/overrides/Gio.py:42: Warning: corrupted double-linked list detected
  return Gio.Application.run(self, *args, **kwargs)

Exception in thread Thread-3 (save_file):
Traceback (most recent call last):
  File "/usr/lib/python3.12/threading.py", line 1075, in _bootstrap_inner
    self.run()
  File "/usr/lib/python3.12/threading.py", line 1012, in run
    self._target(*self._args, **self._kwargs)
  File "/app/main_window.py", line 650, in save_file
    self.set_up_auto_mount()
  File "/app/main_window.py", line 900, in set_up_auto_mount
    "cloud_service": cloud_service,
                     ^^^^^^^^^^^^^
UnboundLocalError: cannot access local variable 'cloud_service' where it is not associated with a value
```

The second PC was again unable to mount the disk (manually with `--sync` argument):

```
FileNotFoundError: [Errno 2] No such file or directory: '/[run/user/1000/gvfs/dav:host=cloud.proninyaroslav.ru,ssl=true,user=admin,prefix=%2Fremote.php%2Fwebdav/nas/backup/SaveDesktop/SaveDesktop.json'](http://run/user/1000/gvfs/dav:host=cloud.proninyaroslav.ru,ssl=true,user=admin,prefix=%2Fremote.php%2Fwebdav/nas/backup/SaveDesktop/SaveDesktop.json')
```

Then I tried to set up cloud storage on the second PC again, as you said earlier. And I get the same error as on the first PC:

```
Traceback (most recent call last):
  File "/[app/main_window.py](http://app/main_window.py)", line 754, in cloudDialog_closed
    self.set_up_auto_mount()
  File "/[app/main_window.py](http://app/main_window.py)", line 900, in set_up_auto_mount
    "cloud_service": cloud_service,
                     ^^^^^^^^^^^^^
UnboundLocalError: cannot access local variable 'cloud_service' where it is not associated with a value
```

**Comment by vikdevelop** [comment]
I'll take another look at it and try to fix it in the next few days.

**Comment by vikdevelop** [comment]
So I tried to fix this bug again, and I released a new version, which is already available on Flathub beta to download. You can try it.

**Comment by proninyaroslav** [comment]
Version 3.5.1-beta_2024.12.20

```
Traceback (most recent call last):
  File "/app/main_window.py", line 754, in cloudDialog_closed
    self.set_up_auto_mount()
  File "/app/main_window.py", line 905, in set_up_auto_mount
    "cloud_service": cloud_service,
                     ^^^^^^^^^^^^^
UnboundLocalError: cannot access local variable 'cloud_service' where it is not associated with a value
```

**Comment by vikdevelop** [comment]
Please try this test build using this command (but before, remove the beta or stable version of the SaveDesktop app, because, I don't know why, but if you have a multiple version of the app in Flatpak, it causes problems with selecting the cloud folders connected using GNOME Online Accounts):
```
flatpak install --user https://dl.flathub.org/build-repo/152735/io.github.vikdevelop.SaveDesktop.flatpakref
```
After testing, you can install previous versions back.

**Comment by proninyaroslav** [comment]
On the first PC after removing the old version with the data:

```
Exception in thread Thread-3 (save_file):
Traceback (most recent call last):
  File "/usr/lib/python3.12/threading.py", line 1075, in _bootstrap_inner
    self.run()
  File "/usr/lib/python3.12/threading.py", line 1012, in run
    self._target(*self._args, **self._kwargs)
  File "/app/main_window.py", line 650, in save_file
    self.set_up_auto_mount()
  File "/app/main_window.py", line 905, in set_up_auto_mount
    "cloud_service": cloud_service,
                     ^^^^^^^^^^^^^
UnboundLocalError: cannot access local variable 'cloud_service' where it is not associated with a value

```

**Comment by vikdevelop** [comment]
Rather, provide the entire output from opening the application to closing it.

**Comment by proninyaroslav** [comment]
```
$ flatpak run io.github.vikdevelop.SaveDesktop

(savedesktop:2): Adwaita-CRITICAL **: 21:52:20.666: Cannot present AdwAlertDialog 0x555ead16f340 as it's already presented for main_window+MainWindow 0x555eacef2b00

(savedesktop:2): Adwaita-CRITICAL **: 21:52:21.853: Trying to remove a response with id 'ok-rclone' from an AdwAlertDialog, but such a response does not exist

(savedesktop:2): Adwaita-CRITICAL **: 21:52:35.574: Cannot present AdwAlertDialog 0x555eade90cd0 as it's already presented for main_window+MainWindow 0x555eacef2b00
Exception in thread Thread-2 (save_file):
Traceback (most recent call last):
  File "/usr/lib/python3.12/threading.py", line 1075, in _bootstrap_inner
    self.run()
  File "/usr/lib/python3.12/threading.py", line 1012, in run
    self._target(*self._args, **self._kwargs)
  File "/app/main_window.py", line 650, in save_file
    self.set_up_auto_mount()
  File "/app/main_window.py", line 905, in set_up_auto_mount
    "cloud_service": cloud_service,
                     ^^^^^^^^^^^^^
UnboundLocalError: cannot access local variable 'cloud_service' where it is not associated with a value


```

**Comment by vikdevelop** [comment]
Does the periodic saving folder still look similar?
> /run/user/1000/gvfs/dav:host=mydomain.com,ssl=true,user=admin,prefix=%2Fremote.php%2Fwebdav/nas/backup/SaveDesktop/Latest_configuration.sd.tar.gz

**Comment by proninyaroslav** [comment]
`/run/user/1000/gvfs/dav:host=myhost,ssl=true,user=myuser,prefix=%2Fremote.php%2Fwebdav/nas/backup/SaveDesktop/Latest_configuration.sd.tar.gz`

**Comment by vikdevelop** [comment]
So I tried to manually set `/run/user/1000/gvfs/dav:host=mydomain.com,ssl=true,user=admin,prefix=%2Fremote.php%2Fwebdav/nas/backup/SaveDesktop/` as the cloud folder in the "Connect to the cloud storage" dialog, clicked the Apply button and created the `savedesktop-synchronization.sh` file mentioned here with this structure: 
```bash
#!/usr/bin/bash
gio mount dav://admin@mydomain.com/%2Fremote.php%2Fwebdav
sleep 60s
flatpak run io.github.vikdevelop.SaveDesktop --sync
flatpak run io.github.vikdevelop.SaveDesktop --background
python3 /var/home/viktor/.var/app/io.github.vikdevelop.SaveDesktop/cache/tmp/install_flatpak_from_script.py
```
Thus, it should hopefully be no problem.
You can try it by installing this test build:
```
flatpak install --user https://dl.flathub.org/build-repo/152759/io.github.vikdevelop.SaveDesktop.flatpakref
```

**Comment by proninyaroslav** [comment]
On the first PC:

```
Exception in thread Thread-3 (save_file):
Traceback (most recent call last):
  File "/usr/lib/python3.12/threading.py", line 1075, in _bootstrap_inner
    self.run()
  File "/usr/lib/python3.12/threading.py", line 1012, in run
    self._target(*self._args, **self._kwargs)
  File "/app/main_window.py", line 650, in save_file
    self.set_up_auto_mount()
  File "/app/main_window.py", line 863, in set_up_auto_mount
    cfile_subtitle = settings.get_default_value("periodic-saving-folder") or self.cfileRow.get_subtitle() or ""
                                                                             ^^^^^^^^^^^^^
AttributeError: 'MainWindow' object has no attribute 'cfileRow'. Did you mean: 'file_row'?
```

There are no errors on the second PC, but when trying to synchronize manually, it says that synchronization is not set up.

**Comment by vikdevelop** [comment]
Try this build, which hopefully will fix this bug:
```bash
flatpak install --user https://dl.flathub.org/build-repo/153202/io.github.vikdevelop.SaveDesktop.flatpakref
```
I tried to use the `/run/user/1000/gvfs/dav:host=mydomain.com,ssl=true,user=admin,prefix=%2Fremote.php%2Fwebdav/nas/backup/SaveDesktop/` folder in the "Connect to the cloud storage dialog" (by manually editing in the configuration file) and in principle it should no longer be a problem to get `cloud_service` and similar variables.

> There are no errors on the second PC, but when trying to synchronize manually, it says that synchronization is not set up.

Do you have selected a Manually option as the periodic synchronization interval in the "Connect to the cloud storage dialog"? If yes, then, it is a new bug, which this build unfortuanetly doesn't fix yet. So, try to select another interval, except Never and Manually.

**Comment by proninyaroslav** [comment]
No more erors on the first PС. On the second PC the initial setup goes fine, but if I try to sync it, it can't mount the disk.

```
$ flatpak run io.github.vikdevelop.SaveDesktop --sync
Saving immediately
saving settings from the Dconf database
saving Gtk settings
saving backgrounds
saving icons
saving themes
saving fonts
saving list of installed Flatpak apps
saving desktop environment configuration files
creating the configuration archive
moving the configuration archive to the user-defined directory
Configuration saved.
Traceback (most recent call last):
  File "/app/bin/savedesktop", line 35, in <module>
    from network_sharing import Syncing
  File "/app/network_sharing.py", line 132, in <module>
    Syncing()
  File "/app/network_sharing.py", line 18, in __init__
    self.get_sync_interval()
  File "/app/network_sharing.py", line 27, in get_sync_interval
    self.check_sync_date()
  File "/app/network_sharing.py", line 67, in check_sync_date
    self.download_config()
  File "/app/network_sharing.py", line 76, in download_config
    self.get_pb_info()
  File "/app/network_sharing.py", line 101, in get_pb_info
    with open(os.path.join(settings['file-for-syncing'], "SaveDesktop.json")) as data:
         ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
FileNotFoundError: [Errno 2] No such file or directory: '/run/user/1000/gvfs/dav:host=host,ssl=true,user=user,prefix=%2Fremote.php%2Fwebdav/nas/backup/SaveDesktop/SaveDesktop.json'
```

**Comment by vikdevelop** [comment]
Does the `~/.var/app/io.github.vikdevelop.SaveDesktop/data/savedesktop-synchronization.sh` file exist? If yes, the cloud drive will be mounted on the next login to the system. Possibly you can open the mentioned file and copy the command defined on the first line and check if it is correct or not. If you get an empty or "Location is already mounted" message, it means the command works.

**Comment by proninyaroslav** [comment]
```
gio: dav://admin@cloud.proninyaroslav.ru/%2Fremote.php%2Fwebdav: volume doesn?t implement mount
```

> If yes, the cloud drive will be mounted on the next login to the system

I log out after setup. And nothing happened.

**Comment by proninyaroslav** [comment]
It seems that `gio mount` doesn't accept percent encoded characters.

**Comment by vikdevelop** [comment]
It is a really strange. If I use the `/run/user/1000/gvfs/dav:host=mydomain.com,ssl=true,user=admin,prefix=%2Fremote.php%2Fwebdav/nas/backup/SaveDesktop/`, the app converts it to the `gio mount dav://admin@mydomain.com/%2Fremote.php%2Fwebdav`, so without problems. 
So, I suggest you to do following:
1. Open the Nautilus (Files) app
2. Go to your Nextcloud server
3. Press the Ctrl+L keyboard shortcut to copy the location
4. Open the already mentioned file (`savedesktop-synchronization.sh`) and paste the copied location instead of `user@host/%2Fremote.php%2Fwebdav` text.

**Comment by vikdevelop** [comment]
Possibly try to use `gio mount dav://admin@mydomain.com` only, instead of `gio mount dav://admin@mydomain.com/%2Fremote.php%2Fwebdav`...
When you open Nautilus (Files), navigate to your Nextcloud drive, then press Ctrl+L, what does that location look like? Maybe the `/%2Fremote.php%2Fwebdav `doesn't even need to go there... I don't know, I've never used Nextcloud.

**Comment by proninyaroslav** [comment]
I got: `HTTP: Moved Permanently`:
```
$ gio mount dav://user@host/remote.php/webdav
```

Probably because my server is set to HTTPS and HTTP is redirected, but GIO can't handle this redirect.
I decided to use `davs` instead of `dav` and it worked:

```
$ gio mount davs://user@host/remote.php/webdav
Authentication required
Enter password for "Nextcloud":
Password:
```

**Comment by vikdevelop** [comment]
In that case, it is, unfortunately, necessary to mounting the drive and syncing manually.

**Comment by proninyaroslav** [comment]
In theory, it's possible to somehow take a key from GNOME Keyring that is unlocked at the moment of login? After all, Nautilus is capable of doing this.

**Comment by vikdevelop** [comment]
You may try to enter this command, which should show a GUI for entering login details and possibly save them to a GNOME Keyring:
```bash
gio mount davs://host/remote.php/webdav
```

**Comment by vikdevelop** [comment]
> In theory, it's possible to somehow take a key from GNOME Keyring that is unlocked at the moment of login? After all, Nautilus is capable of doing this.

Nautilus also allows mounting remote drives using this command:
```bash
nautilus davs://user@host/remote.php/webdav
```
I have tried it with Google and Microsoft OneDrive, but it should work with Nextcloud also. The only negative is that the Nautilus window will open when using this command, which is not wanted. But I didn't find a better way.

**Comment by vikdevelop** [comment]
> In theory, it's possible to somehow take a key from GNOME Keyring that is unlocked at the moment of login? After all, Nautilus is capable of doing this.

Nautilus also allows mounting remote drives using this command:
```bash
nautilus davs://user@host/remote.php/webdav
```
I have tried it with Google and Microsoft OneDrive, but it should work with Nextcloud also. The only negative is that the Nautilus window will open when using this command, which is not wanted. But I didn't find a better way.
You can try it.

**Comment by vikdevelop** [comment]
I finally solved it so that once you select the periodic saving folder in the "Set up sync file" dialog box and/or the cloud folder in the "Connect to cloud storage" dialog box on any computer, log out of the system, and then log back in, Nautilus opens a dialog box to enter the password for the Nextcloud drive. This password is then saved to the keyring (assuming the "Remember password" option is enabled), allowing you to use GIO directly on subsequent system starts, so it will connect in the background, i.e. on subsequent logins to the system the Nautilus window will not open and only GIO will be used.

In my opinion, this is a more secure solution than having SaveDesktop pull data from the GNOME keyring.
The changes are already available in Flathub Beta, but will be available in the stable version of Flathub in a few hours.

**Comment by proninyaroslav** [comment]
It's not published yet (either in beta or stable), but as soon as it is, I'll test it.

**Comment by vikdevelop** [comment]
It is already published. Check, if you still have installed the testing version, using this command: `flatpak list | grep io.github.vikdevelop.SaveDesktop`
If you see the `test` text near the 3.5 version, it means you have installed the test version, which doesn't receive any updates. So, remove it, and install the stable or beta version using: `flatpak install io.github.vikdevelop.SaveDesktop//stable`

**Comment by proninyaroslav** [comment]
I did periodic synchronization, tomorrow I will check how the automount will work.

**Comment by proninyaroslav** [comment]
Seems works fine. Thank you!

**Comment by proninyaroslav** [comment]
Encountered a new error. This time I decided to logout and login in to apply the sync changes, but after logging in I got a message from `abrt`. After that I got a message from `SaveDesktop` that the sync was successful, but in fact it didn't happen (I can tell by some of the apps I installed this week):

`reason: notify-send killed by SIGTRAP`
`cmdline: notify-send $'[Errno 103] Software caused connection abort: /[run/user/1000/gvfs/dav:host=host,ssl=true,user=user,prefix=%2Fremote.php%2Fwebdav/nas/backup/SaveDesktop/Latest_configuration.sd.tar.gz'](http://run/user/1000/gvfs/dav:host=host,ssl=true,user=user,prefix=%2Fremote.php%2Fwebdav/nas/backup/SaveDesktop/Latest_configuration.sd.tar.gz') -i io.github.vikdevelop.SaveDesktop-symbolic`
`pwd: /home/user/.var/app/io.github.vikdevelop.SaveDesktop/cache/tmp/syncing`

I can provide more information from the `abrt` report if needed.

**Comment by vikdevelop** [comment]
Provide a full output from this command instead:
```
flatpak run io.github.vikdevelop.SaveDesktop --sync
```
From the provided output from the `abrt` command, I can't determine, where the error is.

**Comment by proninyaroslav** [comment]
When I tried to do this I  right away got that it was already synchronized.

**Comment by vikdevelop** [comment]
Try:
```
rm /home/viktor/.var/app/io.github.vikdevelop.SaveDesktop/data/sync-info.json && flatpak run io.github.vikdevelop.SaveDesktop --sync
```
This resets the configured date of syncing and starts the synchronization.

**Comment by proninyaroslav** [comment]
Now the synchronization went without problems. Maybe I logged out during the synchronization and it broke it

**Comment by proninyaroslav** [comment]
@vikdevelop 
I think it is necessary to make a notification about the start of sync, in addition to the notification about the end. Since the user may not know that sync is currently taking place and reboot the system or logout. And this causes a crash and sync doesn't occur until the end.

**Comment by vikdevelop** [comment]
Alright, I will add it to the next micro version, which will be `3.5.2`.
