### ISSUE TITLE
How do you code your GTK applications with Python ?

### ISSUE THREAD

**Issue by alcapitan** [vikdevelop/SaveDesktop#36]
Hello,
First, excuse me for spamming your "Issues" page, but I didn't find any other way to contact you.

I'm a French 17 years old coder and I'm interested to start coding with GTK on Python.
I have already tried a few things but without success, actually I have not yet found a really understandable course..
I discovered you by SaveDesktop and I think your code is very understandable and clear, even better than some tutorials on the Internet !

So, I wonder what documentations and courses did you follow to learn GTK on Python ?

I hope you will understand my disruption here, and I congratulate you for yours projects because it looks really well done !
Thank you for answering,

**Comment by vikdevelop** [comment]
Hello,
You just need to understand the Python syntax, and then the GTK or Libadwaita documentation in C programming language will be enough: [Libadwaita documentation](https://gnome.pages.gitlab.gnome.org/libadwaita/doc/main/index.html), [GTK4 documentation](https://docs.gtk.org/gtk4/index.html)

**Comment by alcapitan** [comment]
Ok, thanks for your answer. I will try working on it !
