### ISSUE TITLE
no update version on app information

### ISSUE THREAD

**Issue by albanobattistella** [vikdevelop/SaveDesktop#43]
Hi,

I noticed that the app is not updated.
for example...I still have version 1.0.
Could you check it?
thanks!
Regards.
A.

**Comment by vikdevelop** [comment]
Hello,
Are you referring to version 1.0, which is displayed in the About dialog of the SaveDesktop application?

**Comment by albanobattistella** [comment]
> Hello, Are you referring to version 1.0, which is displayed in the About dialog of the SaveDesktop application?

yes!

**Comment by vikdevelop** [comment]
When I release the next version, it will be fixed.
