### ISSUE TITLE
Application version is still displayed as 1.0

### ISSUE THREAD

**Issue by mcmxcdev** [vikdevelop/SaveDesktop#46]
This version should probably be dynamic based on the current release version.

Also, there is a "copy to clipboard" functionality with it which doesn't seem useful IMO.

![image](https://user-images.githubusercontent.com/16797721/229338522-6d8b9c3a-472e-4aae-8525-b325f6dbb481.png)

**Comment by vikdevelop** [comment]
When I release the next version, this bug will be fixed.

**Comment by vikdevelop** [comment]
New version with fixed this bug has been published on Flathub. It availables to download will be in a few hours.
