### ISSUE TITLE
App icon following GNOME's guidelines

### ISSUE THREAD

**Issue by bragefuglseth** [vikdevelop/SaveDesktop#62]
SaveDesktop utilizes GNOME's platform libraries and design guidelines, but the current app icon looks out of place among other GNOME apps. I think the app would benefit from having an icon with [GNOME's distinct visual style](https://developer.gnome.org/hig/guidelines/app-icons.html). Even though the app is cross-desktop, it already looks out of place *everywhere*, so why not have it well-integrated in at least one place? 😊️

I can design one if you want me to. I'll start brainstorming, but feel free to stop me if you don't consider it to be necessary :smile:

**Comment by bragefuglseth** [comment]
My initial metaphor idea is the traditional floppy disk icon. This was literally used to store the contents of your system back in the days, so I think it's a solid choice!

**Comment by vikdevelop** [comment]
Hello,
I was thinking about a better icon, but didn't know how to make it match the Gnome HIG. So feel free to suggest an icon and paste it here. Thank you very much in advance for your help with the new icon!

**Comment by bragefuglseth** [comment]
I'll put the icon files in the appropriate locations and open a PR when it's finished
