### ISSUE TITLE
Configuration folder not opening

### ISSUE THREAD

**Issue by xplosionmind** [vikdevelop/SaveDesktop#70]
After clicking on “save configuration”, a message shows up telling that the configuration has been successfully saved, but when clicking the “open configuration folder” next to it, nothing happens.

**Comment by vikdevelop** [comment]
Hello, run SaveDesktop in terminal (`flatpak run io.github.vikdevelop.SaveDesktop`) and paste output from this command here.

**Comment by xplosionmind** [comment]
Thanks for your reply, @vikdevelop! Here is the log:

```
flatpak run io.github.vikdevelop.SaveDesktop

mkdir: cannot create directory ‘None/SaveDesktop/’: No such file or directory
mkdir: cannot create directory ‘None/SaveDesktop/archives/’: No such file or directory
cp: cannot stat '/home/tommi/.local/share/gnome-background-properties': No such file or directory
cp: cannot stat '/home/tommi/.local/share/nautilus-python': No such file or directory
cp: cannot stat '/home/tommi/.local/share/gnome-control-center': No such file or directory
mv: cannot move 'ThinkTommi.sd.tar.gz' to 'None/SaveDesktop/archives/': No such file or directory
tar: ./gnome-shell/extensions/appindicatorsupport@rgcjonas.gmail.com: file changed as we read it
tar: ./gnome-shell/extensions: file changed as we read it
tar: ./gnome-shell: file changed as we read it
tar: .: file changed as we read it
Failed to open '/home/tommi/None/SaveDesktop/.2023-04-27/None/SaveDesktop/archives': No such file or directory
```

**Comment by vikdevelop** [comment]
You probably don't have a download folder set up. To set up a download folder, use this command:
`xdg-user-dirs-update --set DOWNLOAD (Find the download folder, it can be /home/user/Downloads (en), /home/user/Herunterladen (de) in the file manager)`

**Comment by xplosionmind** [comment]
Thanks a lot! It works now. I believe it would be nice if users could choose the destination folder within the GUI.
