### ISSUE TITLE
Choose a custom destination directory

### ISSUE THREAD

**Issue by xplosionmind** [vikdevelop/SaveDesktop#72]
Add the possibility of choosing an arbitrary custom destination directory where to save the configuration.

**Comment by vikdevelop** [comment]
Hello, when I tried it (selecting a folder using FileChooserNative), there was a problem with compressing the archive to tar.gz, and somewhere there was a problem with the SaveDesktop loading the selected folder itself. So I won't add this feature yet and it will be saved as before. Anyway, I will try to implement it in another way in the future.
