### ISSUE TITLE
App defaults to German even when system language is English

### ISSUE THREAD

**Issue by DeeBeeDouble** [vikdevelop/SaveDesktop#82]
The app is not detecting my system language correctly and defaults to German instead of English. After looking at the code, I discovered that the issue is being caused by this code block:

```
elif "de" in subprocess.getoutput('locale | grep "LANG"'):
    lang = 'de.json'
```

The above code is causing the app to assume that the system language is German, even when the system language is set to English. This is because on my system, the output of the `locale | grep "LANG"` command contains an error message that includes the letters "DE", which causes the code to incorrectly identify the language.

To solve this issue, I would suggest replacing the above code with:

```
elif "de" in subprocess.getoutput('locale | grep "LANG"').split("LANG=")[1][:2]:
    lang = 'de.json'
```
This solves the problem on my system. Although I did not test it for any unwanted side effects, it might have on other systems. But I am pretty sure that it should be fine.

Alternatively, you could also determine the language using the following code:

```
import locale
lang, _ = locale.getlocale()
syslang = lang + ".json"
```
Then just change the names of the language files accordingly.
To me, this just seems like a much cleaner solution. But maybe there is a reason why you wouldn't want to use this, I don't know.

**Comment by vikdevelop** [comment]
Hello, what do you think about this commit? [`13c0e69`](https://github.com/vikdevelop/SaveDesktop/commit/13c0e69397e47c63455846192ffcccfc2d4423e3)

**Comment by DeeBeeDouble** [comment]
> Hello, what do you think about this commit? [`13c0e69`](https://github.com/vikdevelop/SaveDesktop/commit/13c0e69397e47c63455846192ffcccfc2d4423e3)

This does seem to do the trick, but only after changing

` p_lang = locale.getlocale(locale.LC_MESSAGES)[0]` 
to  
`p_lang = locale.getlocale()[0]`

Otherwise, the output will just be "None"

Also, with this approach, I do not see any need for `syslang = r_lang + ".json"`, as you're already adding the .json later.

Lastly, I do not know if just removing three characters will work for every language there is.

**Comment by vikdevelop** [comment]
In commit [`b173c89`](https://github.com/vikdevelop/SaveDesktop/commit/b173c89790dca03f5526fb15e3cd4740d4b8c2e6) is already fixed. Yes, removing three characters works in more or less any language, because most of them are in the form xx_XX (e.g. en_GB)

**Comment by DeeBeeDouble** [comment]
> In commit [`b173c89`](https://github.com/vikdevelop/SaveDesktop/commit/b173c89790dca03f5526fb15e3cd4740d4b8c2e6) is already fixed.

Perfect.

>Yes, removing three characters works in more or less any language, because most of them are in the form xx_XX (e.g. en_GB)

Alright then, good to hear.
