### ISSUE TITLE
[Feature] Save Gnome Extensions and their Settings

### ISSUE THREAD

**Issue by Heus-Sueh** [vikdevelop/SaveDesktop#98]
it would be really cool if the app could save the extensions that are installed as well as the settings that have been made in the extensions.

it would be great if the app could save the settings of the following extensions: dash to dock, dash to panel, blur my shell, aylur's widgets and maybe user themes

**Comment by vikdevelop** [comment]
Hello, SaveDesktop can save all installed extensions in `~/.local/share/gnome-shell/extensions` and settings stored in Dconf (most extensions using Dconf to store their configuration), so it would not be a problem.

**Comment by Heus-Sueh** [comment]
> Hello, SaveDesktop can save all installed extensions in `~/.local/share/gnome-shell/extensions` and settings stored in Dconf (most extensions using Dconf to store their configuration), so it would not be a problem.

strange, because I had a bizarre bug, I saved my desktop settings and tried to import it and I logged out when I logged in again gnome was back to stock with no modifications and with gnome tour open :thinking:

**Comment by vikdevelop** [comment]
Run SaveDesktop from terminal and insert output here.

**Comment by Heus-Sueh** [comment]
❯ flatpak run io.github.vikdevelop.SaveDesktop

cp: cannot stat '/var/home/heus/.local/share/gnome-background-properties': No such file or directory
cp: cannot stat '/var/home/heus/.local/share/gnome-control-center': No such file or directory
tar: ./icons/Colloid-light: file changed as we read it
tar: ./icons: file changed as we read it
tar: .: file changed as we read it

**Comment by vikdevelop** [comment]
Sorry I didn't specify, I meant the output from the terminal when importing the configuration.

**Comment by Heus-Sueh** [comment]
> Sorry I didn't specify, I meant the output from the terminal when importing the configuration.

❯ flatpak run io.github.vikdevelop.SaveDesktop

/app/main_window.py:455: DeprecationWarning: Gtk.FileChooserNative.new is deprecated
  self.file_chooser = Gtk.FileChooserNative.new(_["import_fileshooser"].format(self.environment), \
/app/main_window.py:461: DeprecationWarning: Gtk.FileChooser.add_filter is deprecated
  self.file_chooser.add_filter(self.file_filter)
/app/main_window.py:550: DeprecationWarning: Gtk.FileChooser.get_file is deprecated
  file = dialog.get_file()
cp: cannot stat './installed_flatpaks.sh': No such file or directory
cp: cannot stat './gnome-background-properties': No such file or directory
cp: cannot stat './gnome-control-center': No such file or directory`

**Comment by Heus-Sueh** [comment]
i think the problem is that it fails to save the extensions that are enabled

example: if I save my current configuration with extensions enabled and disable them and try to import the settings, it doesn't have a method to know which extensions were enabled so it goes back to gnome stock.

I think that's what's going on

**Comment by vikdevelop** [comment]
I tried import configuration in other user account, and no problems. However, it could become, the extensions disables, then just enable switch "Use extensions" in application Extensions Manager (`com.mattjakeman.ExtensionManager`) or GNOME extension manager and the extensions which has been enabled when saving configuration will be enabled (if it is available for GNOME Shell version).

**Comment by Heus-Sueh** [comment]
> I tried import configuration in other user account, and no problems. However, it could become, the extensions disables, then just enable switch "Use extensions" in application Extensions Manager (`com.mattjakeman.ExtensionManager`) or GNOME extension manager and the extensions which has been enabled when saving configuration will be enabled (if it is available for GNOME Shell version).

ok, isn't there a way to automatically enable extensions when importing settings?

**Comment by vikdevelop** [comment]
In the most cases works without problems, extensions enables automatically, but sometimes it does not work, so it is need enable switch "Use extensions". I do not know, what's causing this.


> i think the problem is that it fails to save the extensions that are enabled
> 
> example: if I save my current configuration with extensions enabled and disable them and try to import the settings, it doesn't have a method to know which extensions were enabled so it goes back to gnome stock.
> 
> I think that's what's going on

SaveDesktop can save both enabled and disabled extensions, I have e.g. ArcMenu extension that is disabled, and after importing configuration it is disabled and other extensions are enabled.

**Comment by vikdevelop** [comment]
In the most cases works without problems, extensions enables automatically, but sometimes it does not work, so it is need enable switch "Use extensions".

> i think the problem is that it fails to save the extensions that are enabled
> 
> example: if I save my current configuration with extensions enabled and disable them and try to import the settings, it doesn't have a method to know which extensions were enabled so it goes back to gnome stock.
> 
> I think that's what's going on



Check size of extensions folder in archive and compare it with size in ~/.local/share/gnome-shell extensions.

**Comment by Heus-Sueh** [comment]
> In the most cases works without problems, extensions enables automatically, but sometimes it does not work, so it is need enable switch "Use extensions".
> 
> > i think the problem is that it fails to save the extensions that are enabled
> > example: if I save my current configuration with extensions enabled and disable them and try to import the settings, it doesn't have a method to know which extensions were enabled so it goes back to gnome stock.
> > I think that's what's going on
> 
> Check size of extensions folder in archive and compare it with size in ~/.local/share/gnome-shell extensions.

both folders are the same size :thinking:

**Comment by vikdevelop** [comment]
In that case SaveDesktop saved installed gnome extensions correctly. Problem could be with properties `enabled-extensions` and `disabled-extensions`. Enabled extensions are listed in `/org/gnome/shell/enabled-extensions` and disabled extensions are listed in: `/org/gnome/shell/disabled-extensions`. You can use Dconf editor to show this properties. 
What Linux distro and version of GNOME are you using?

**Comment by vikdevelop** [comment]
It may happen that the `/org/gnome/shell/disable-user-extensions` Dconf property is enabled when you log back in, and this will then disable user extensions. I will try to implement it so that after importing the configuration and logging back in, this feature is always checked and possibly enabled if disabled and you can then install a test build and check if it works.

**Comment by vikdevelop** [comment]
> It may happen that the `/org/gnome/shell/disable-user-extensions` Dconf property is enabled when you log back in, and this will then disable user extensions. I will try to implement it so that after importing the configuration and logging back in, this property is always checked and possibly enabled if disabled and you can then install a test build and check if it works.

I added support for enabling the Dconf property (as I wrote above). If you want to try a test build, use these commands:
```bash
git clone https://github.com/vikdevelop/SaveDesktop
cd SaveDesktop
flatpak-builder build *.yaml --install --user
# You may need to install org.gnome.Sdk runtime (flatpak install runtime/org.gnome.Sdk/x86_64/44)
```
Let me know, if it is worked or not.

**Comment by Heus-Sueh** [comment]
> > It may happen that the `/org/gnome/shell/disable-user-extensions` Dconf property is enabled when you log back in, and this will then disable user extensions. I will try to implement it so that after importing the configuration and logging back in, this property is always checked and possibly enabled if disabled and you can then install a test build and check if it works.
> 
> I added support for enabling the Dconf property (as I wrote above). If you want to try a test build, use these commands:
> 
> ```shell
> git clone https://github.com/vikdevelop/SaveDesktop
> cd SaveDesktop
> flatpak-builder build *.yaml --install --user
> # You may need to install org.gnome.Sdk runtime (flatpak install runtime/org.gnome.Sdk/x86_64/44)
> ```
> 
> Let me know, if it is worked or not.

sorry for the delay in answering, I'm going to test this tomorrow around here it's already quite late

**Comment by Heus-Sueh** [comment]
it gives me this error:

>❯ git clone https://github.com/vikdevelop/SaveDesktop
cd SaveDesktop
Cloning into 'SaveDesktop'...
remote: Enumerating objects: 2779, done.
remote: Counting objects: 100% (1236/1236), done.
remote: Compressing objects: 100% (533/533), done.
remote: Total 2779 (delta 849), reused 1049 (delta 702), pack-reused 1543
Receiving objects: 100% (2779/2779), 1.11 MiB | 2.42 MiB/s, done.
Resolving deltas: 100% (1671/1671), done.
❯ cd SaveDesktop
cd: no such file or directory: SaveDesktop
❯ flatpak-builder build *.yaml --install --user
Downloading sources
Initializing build dir
Committing stage init to cache
Starting build of io.github.vikdevelop.SaveDesktop
========================================================================
Building module savedesktop in /var/home/heus/SaveDesktop/.flatpak-builder/build/savedesktop-1
========================================================================
Running: install -Dm755 -t /app/bin run.sh
Running: install -Dm755 -t /app src/main_window.py
Running: install -Dm755 -t /app src/periodic_saving.py
Running: install -Dm755 -t /app src/install_flatpak_from_script.py
Running: install -Dm755 -t /app src/backup_flatpaks.sh
Running: install -D -t /app/share build-beta.sh
Running: install -D -t /app/share/applications flatpak/io.github.vikdevelop.SaveDesktop.desktop
Running: install -D -t /app/share/icons/hicolor/scalable/apps flatpak/icons/io.github.vikdevelop.SaveDesktop.svg
Running: install -D -t /app/share/icons/hicolor/scalable/apps flatpak/icons/io.github.vikdevelop.SaveDesktop.Devel.svg
Running: install -D -t /app/share/icons/hicolor/symbolic/apps flatpak/icons/io.github.vikdevelop.SaveDesktop-symbolic.svg
Running: install -D -t /app/share/icons/hicolor/128x128/apps flatpak/symbolic-icons/exclamation_mark.png
Running: install -D -t /app/share/icons/hicolor/128x128/apps flatpak/symbolic-icons/desktop-symbolic.svg
Running: install -D -t /app/share/icons/hicolor/128x128/apps flatpak/symbolic-icons/list-view.svg
install: cannot stat 'flatpak/symbolic-icons/list-view.svg': No such file or directory
Error: module savedesktop: Child process exited with code 1

**Comment by vikdevelop** [comment]
> it gives me this error:
> 
> >❯ git clone https://github.com/vikdevelop/SaveDesktop
> cd SaveDesktop
> Cloning into 'SaveDesktop'...
> remote: Enumerating objects: 2779, done.
> remote: Counting objects: 100% (1236/1236), done.
> remote: Compressing objects: 100% (533/533), done.
> remote: Total 2779 (delta 849), reused 1049 (delta 702), pack-reused 1543
> Receiving objects: 100% (2779/2779), 1.11 MiB | 2.42 MiB/s, done.
> Resolving deltas: 100% (1671/1671), done.
> ❯ cd SaveDesktop
> cd: no such file or directory: SaveDesktop
> ❯ flatpak-builder build *.yaml --install --user
> Downloading sources
> Initializing build dir
> Committing stage init to cache
> Starting build of io.github.vikdevelop.SaveDesktop
> ========================================================================
> Building module savedesktop in /var/home/heus/SaveDesktop/.flatpak-builder/build/savedesktop-1
> ========================================================================
> Running: install -Dm755 -t /app/bin run.sh
> Running: install -Dm755 -t /app src/main_window.py
> Running: install -Dm755 -t /app src/periodic_saving.py
> Running: install -Dm755 -t /app src/install_flatpak_from_script.py
> Running: install -Dm755 -t /app src/backup_flatpaks.sh
> Running: install -D -t /app/share build-beta.sh
> Running: install -D -t /app/share/applications flatpak/io.github.vikdevelop.SaveDesktop.desktop
> Running: install -D -t /app/share/icons/hicolor/scalable/apps flatpak/icons/io.github.vikdevelop.SaveDesktop.svg
> Running: install -D -t /app/share/icons/hicolor/scalable/apps flatpak/icons/io.github.vikdevelop.SaveDesktop.Devel.svg
> Running: install -D -t /app/share/icons/hicolor/symbolic/apps flatpak/icons/io.github.vikdevelop.SaveDesktop-symbolic.svg
> Running: install -D -t /app/share/icons/hicolor/128x128/apps flatpak/symbolic-icons/exclamation_mark.png
> Running: install -D -t /app/share/icons/hicolor/128x128/apps flatpak/symbolic-icons/desktop-symbolic.svg
> Running: install -D -t /app/share/icons/hicolor/128x128/apps flatpak/symbolic-icons/list-view.svg
> install: cannot stat 'flatpak/symbolic-icons/list-view.svg': No such file or directory
> Error: module savedesktop: Child process exited with code 1
> 
> 
> 

I fixed it. Try to clone and build again.

**Comment by vikdevelop** [comment]
I already fixed it, try again.

**Comment by Heus-Sueh** [comment]
> Finishing app
Exporting share/applications/io.github.vikdevelop.SaveDesktop.desktop
Exporting share/icons/hicolor/scalable/apps/io.github.vikdevelop.SaveDesktop.svg
Exporting share/icons/hicolor/scalable/apps/io.github.vikdevelop.SaveDesktop.Devel.svg
Exporting share/icons/hicolor/symbolic/apps/io.github.vikdevelop.SaveDesktop-symbolic.svg
Not exporting share/icons/hicolor/128x128/apps/exclamation_mark.png, non-allowed export filename
Not exporting share/icons/hicolor/128x128/apps/desktop-symbolic.svg, non-allowed export filename
Not exporting share/icons/hicolor/128x128/apps/list-view.png, non-allowed export filename
Not exporting share/icons/hicolor/128x128/apps/edit-symbolic.svg, non-allowed export filename
Exporting share/appdata/io.github.vikdevelop.SaveDesktop.appdata.xml
Please review the exported files and the metadata
Committing stage finish to cache
Exporting io.github.vikdevelop.SaveDesktop to repo
Commit: 96d08e97d0e6527bb3c376eb40c2f11816622538b0fd7052961c25a030d4e2cb
Metadata Total: 69
Metadata Written: 2
Content Total: 43
Content Written: 0
Content Bytes Written: 0 (0 bytes)
Updating runtime/org.gnome.Platform.Locale/x86_64/44
Updating runtime/org.gtk.Gtk3theme.adw-gtk3/x86_64/3.22
Installing app/io.github.vikdevelop.SaveDesktop/x86_64/master
Error: Failed to install io.github.vikdevelop.SaveDesktop: Could not connect: No such file or directory
Install failed: Child process exited with code 1

**Comment by vikdevelop** [comment]
Try to use this command `sudo flatpak-builder build *.yaml --install --system --force-clean`

**Comment by Heus-Sueh** [comment]
> `sudo flatpak-builder build *.yaml --install --system --force-clean`

sorry again for the delay in responding, it is giving this error:

Cloning into 'SaveDesktop'...
remote: Enumerating objects: 2782, done.
remote: Counting objects: 100% (1239/1239), done.
remote: Compressing objects: 100% (536/536), done.
remote: Total 2782 (delta 850), reused 1047 (delta 702), pack-reused 1543
Receiving objects: 100% (2782/2782), 1.11 MiB | 10.16 MiB/s, done.
Resolving deltas: 100% (1672/1672), done.
❯ cd SaveDesktop
❯ sudo flatpak-builder build *.yaml --install --system --force-clean
[sudo] password for heus: 
error: org.gnome.Sdk/x86_64/44 not installed
Failed to init: Unable to find sdk org.gnome.Sdk version 44
❯ flatpak install org.gnome.Sdk/x86_64/44
Looking for matches…
Remotes found with refs similar to ‘org.gnome.Sdk/x86_64/44’:

   1) ‘flathub-1’ (system)
   2) ‘flathub’ (user)

Which do you want to use (0 to abort)? [0-2]: 2
Skipping: org.gnome.Sdk/x86_64/44 is already installed

**Comment by vikdevelop** [comment]
I created test build, try this commands`flatpak install --user https://dl.flathub.org/build-repo/30551/io.github.vikdevelop.SaveDesktop.flatpakref` or `flatpak install https://dl.flathub.org/build-repo/30551/io.github.vikdevelop.SaveDesktop.flatpakref`.

**Comment by Heus-Sueh** [comment]
> I created test build, try to use this command `flatpak install --user https://dl.flathub.org/build-repo/30551/io.github.vikdevelop.SaveDesktop.flatpakref` or `flatpak install https://dl.flathub.org/build-repo/30551/io.github.vikdevelop.SaveDesktop.flatpakref`.

I'm having another problem too, the program says it saved the file successfully but in the terminal it says it couldn't move the file to the directory and the file doesn't appear in the Downloads/Save Desktop folder even though I've given permissions to it access home:
![image](https://github.com/vikdevelop/SaveDesktop/assets/98482469/4e782f57-0525-4f5f-b56e-b60056938d26)
![image](https://github.com/vikdevelop/SaveDesktop/assets/98482469/05c04c39-aba9-465e-8ed1-cf1a49446489)
![image](https://github.com/vikdevelop/SaveDesktop/assets/98482469/c0eb8ce2-8976-4945-b636-4b782cbe7985)

**Comment by Heus-Sueh** [comment]
> I created test build, try to use this command `flatpak install --user https://dl.flathub.org/build-repo/30551/io.github.vikdevelop.SaveDesktop.flatpakref` or `flatpak install https://dl.flathub.org/build-repo/30551/io.github.vikdevelop.SaveDesktop.flatpakref`.

I tested this build and the extensions were activated automatically, I tested it as follows:

i saved the settings, disabled the Extension Manager "Use Extensions" button and imported the settings and logged out and logged back in and the extensions were automatically enabled

**Comment by vikdevelop** [comment]
You probably did not set up the Desktop folder correctly because in the log it is not `/home/USER/Desktop `or something else but only `/Desktop`, so it could be a problem. You can set it correctly with this command:
```
xdg-user-dirs-update --set DESKTOP ~/Desktop
```

**Comment by Heus-Sueh** [comment]
> You probably did not set up the Desktop folder correctly because in the log it is not `/home/USER/Desktop `or something else but only `Desktop/`, so it could be a problem. You can set it correctly with this command:
> 
> ```
> xdg-user-dirs-update --set DESKTOP ~/Desktop
> ```
I did this command but the error persists, do I need to restart?

**Comment by vikdevelop** [comment]
What Linux distro are you using?

**Comment by vikdevelop** [comment]
Try to save to another folder. I was wondering what Linux distro are you using?

**Comment by Heus-Sueh** [comment]
> It is not necessary to restart it. Try to save to another folder. I was wondering what Linux distro are you using?

I'm using fedora silverblue, I forgot to mention this detail, it only leaves many folders read-only, maybe that's the problem

**Comment by vikdevelop** [comment]
Probably yes, this is a problem because I am using SaveDesktop on Fedora Workstation (and other distros like Linux Mint, Pop! OS, Manjaro, Ubuntu, elementary OS) and I have not had any problems. I never tested SaveDesktop on Fedora Silverblue.

**Comment by Heus-Sueh** [comment]
> Probably yes, this is a problem because I am using SaveDesktop on Fedora Workstation (and other distros like Linux Mint, Pop! OS, Manjaro, Ubuntu, elementary OS) and I have not had any problems. I never tested SaveDesktop on Fedora Silverblue.

I think the problem is something else, I think the home is RW (Read and Write) in Fedora Silverblue only other sensitive folders that are just read-only

**Comment by vikdevelop** [comment]
> I created test build, try to use this command `flatpak install --user https://dl.flathub.org/build-repo/30551/io.github.vikdevelop.SaveDesktop.flatpakref` or `flatpak install https://dl.flathub.org/build-repo/30551/io.github.vikdevelop.SaveDesktop.flatpakref`.

So I tried using SaveDesktop in Fedora Silverblue 38 (in a virtual machine), and saving configuration works without problems to any home directory; I did not have to allow permission in Flatseal. I installed SaveDesktop test release (`app/io.github.vikdevelop.SaveDesktop/x86_64/test`) to the system, not to the home directory. Command for the installation test release I sent in above.

Importing configuration with the test release is also without problems; extensions activate automatically, but you need to remove the dconf file located in `~/.config/dconf/user` (using `rm ~/.config/dconf/user` or using Nautilus) and then import configuration.

**Comment by Heus-Sueh** [comment]
> > I created test build, try to use this command `flatpak install --user https://dl.flathub.org/build-repo/30551/io.github.vikdevelop.SaveDesktop.flatpakref` or `flatpak install https://dl.flathub.org/build-repo/30551/io.github.vikdevelop.SaveDesktop.flatpakref`.
> 
> So I tried using SaveDesktop in Fedora Silverblue 38 (in a virtual machine), and saving configuration works without problems to any home directory; I did not have to allow permission in Flatseal. I installed SaveDesktop test release (`app/io.github.vikdevelop.SaveDesktop/x86_64/test`) to the system, not to the home directory. Command for the installation test release I sent in above.
> 
> Importing configuration with the test release is also without problems; extensions activate automatically, but you need to remove the dconf file located in `~/.config/dconf/user` (using `rm ~/.config/dconf/user` or using Nautilus) and then import configuration.

strange maybe it's my system, for now I'll close this issue
