### ISSUE TITLE
Allow auto import to sync between machines

### ISSUE THREAD

**Issue by 13hannes11** [vikdevelop/SaveDesktop#99]

**Comment by vikdevelop** [comment]
Hello, 
Could you elaborate more on what this is about your feature request? "Allow auto import to sync between machines", from the title, is not clear to me, how you want it implemented.

**Comment by 13hannes11** [comment]
Sorry for not providing more information. I am referring to that the settings have an automatic export function and it would be great to have this functionality for importing.
This way you could setup automatic exporting to a folder that is synced with cloud storage and use it to keep two systems with the same settings.

I hope this makes more sense.

**Comment by vikdevelop** [comment]
So I understand correctly? For example, if you have set up a desktop environment on computer 1, it will automatically be imported to Computer 2. Then, if you make changes in computer 1, they will automatically be imported to computer 2, so you mean syncing. In that case, I am not sure if it would work correctly. It would require access to the network, which is possible in Flatpak, but probably not to view other computers in the network.

**Comment by vikdevelop** [comment]
I do not know, what it is good for. If you want to save configuration periodically to cloud storage, you can connect cloud storage with your file manager and set up a folder for the periodic saving folder.
As for importing configuration periodically same as periodic saving, I cannot imagine it. You need to choose a file for importing configuration, in case periodic saving, there is no need. Also for users it would not be good. I do not think that users would be excited, if the system would be changed "under hands".
So far I will not implement this feature, maybe sometimes in the future.

**Comment by marcinjahn** [comment]
I think the idea is quite good, and it would be pretty useful, but it requires some further investigation.

Imagine that you have two computers. You change a theme, or install some flatpak app on one of them. The other PC would automatically pull these changes (via periodic import). This way, you could have two PCs that are auto-synchronized.

The only issue I see is that the synchronization would work in one direction only. One PC would be the "exporter", the other PC would be the "importer". If you change something on the "importer", the "exporter" would not pull that change.
Perhaps for some such limitation would be alright.

I think it wouldn't be too difficult to enable such functionality in the app. The required changes would be:

- allow periodical export to save the config to a single file - every export saves the config in that one file, overwriting previous content
- add automatic periodic import functionality, where you'd select a file, and that file would be periodically imported
